<?php
/* 통합웹빌더 운영 API — 라우트 ② 방문예약(광고주별 분리 · 접근기록) · 미디어 · 팝업 · SEO · 통계 · 계정 · 로그 · 검색 · 시스템 · 공개 API */
if (!defined('WB_API')) { http_response_code(404); exit; }

/* ================= 방문예약 : 모든 조회 · 검색 · 통계 · 다운로드가 "내 권한의 사이트" 안에서만 동작 (URL 의 site · advertiser 값을 바꿔도 다른 광고주 자료는 나오지 않음) ================= */
function wb_sub_sites($c, $siteParam) { $all = array(); foreach (wb_sites($c['user']) as $s) { if (wb_can($c['user'], (int)$s['id'], 'submissions') || wb_can($c['user'], (int)$s['id'], 'submissions.view')) { $all[] = $s; } } $adv = wb_int(wb_q($c, 'advertiser')); if ($adv) { $all = array_values(array_filter($all, function ($s) use ($adv) { return (int)$s['advertiser_id'] === $adv; })); } if ($siteParam === null || $siteParam === '' || $siteParam === 'all') { return $all; } foreach ($all as $s) { if ((int)$s['id'] === wb_int($siteParam)) { return array($s); } } throw new WbHttpError(403, '해당 사이트의 예약을 볼 권한이 없습니다.'); }
function wb_sub_ids($sites) { $ids = array(); foreach ($sites as $s) { $ids[] = (int)$s['id']; } return $ids; }
function wb_sub_filters($c, $sites) {
  $ids = wb_sub_ids($sites); $where = array('s.site_id IN (' . (count($ids) ? wb_in($ids) : '0') . ')', 's.deleted_at IS NULL'); $params = $ids; $q = $c['query']; $st = wb_statuses();
  if (isset($q['gs']) && $q['gs'] === 'failed') { $where[] = "EXISTS (SELECT 1 FROM google_sheet_sync_logs g WHERE g.reservation_id = s.id AND g.status = 'failed')"; }   /* 알림 › Google Sheets 실패 예약 보기 */
  if (isset($q['status']) && $q['status'] === 'pending') { $where[] = "s.status IN ('new','checking')"; } elseif (!empty($q['status']) && isset($st[$q['status']])) { $where[] = 's.status = ?'; $params[] = $q['status']; }
  if (!empty($q['from'])) { $where[] = 's.created_at >= ?'; $params[] = $q['from'] . ' 00:00:00'; } if (!empty($q['to'])) { $where[] = 's.created_at <= ?'; $params[] = $q['to'] . ' 23:59:59'; }
  if (!empty($q['vfrom'])) { $where[] = 's.visit_date >= ?'; $params[] = $q['vfrom']; } if (!empty($q['vto'])) { $where[] = 's.visit_date <= ?'; $params[] = $q['vto']; } if (!empty($q['vtime'])) { $where[] = 's.visit_time = ?'; $params[] = $q['vtime']; }
  if (!empty($q['assignee']) && wb_int($q['assignee'])) { $where[] = 's.assignee_id = ?'; $params[] = wb_int($q['assignee']); }
  if (!empty($q['name'])) { $where[] = 's.name LIKE ?'; $params[] = '%' . $q['name'] . '%'; } if (!empty($q['phone'])) { $where[] = "REPLACE(s.phone, '-', '') LIKE ?"; $params[] = '%' . preg_replace('/[^0-9]/', '', $q['phone']) . '%'; }
  if (!empty($q['q'])) { $digits = preg_replace('/\D+/', '', (string)$q['q']); $where[] = '(s.name LIKE ? OR s.phone LIKE ? OR s.receipt_no LIKE ? OR s.data_json LIKE ? OR s.memo LIKE ?' . (strlen($digits) >= 3 ? " OR REPLACE(s.phone, '-', '') LIKE ?" : '') . ')'; $like = '%' . $q['q'] . '%'; array_push($params, $like, $like, $like, $like, $like); if (strlen($digits) >= 3) { $params[] = '%' . $digits . '%'; } }
  return array('where' => implode(' AND ', $where), 'params' => $params);
}
/* 고객이 입력한 문의사항 원문 (폼의 여러 줄 입력칸 · 제출 당시 항목 기준) — 목록 미리보기 · 전체 보기용 (DB 원문은 그대로) */
function wb_sub_inquiry($s, $data) {
  if (!is_array($data) || !empty($data['_purged'])) { return ''; }
  $key = ''; foreach ((array)wb_json_safe($s['fields_json'], array()) as $f) { $f = wb_arr($f); if (isset($f['type']) && $f['type'] === 'textarea' && !empty($f['name'])) { $key = $f['name']; break; } }
  if ($key === '') { foreach (array('memo', 'message', 'inquiry', 'question', 'content', 'comment') as $k) { if (isset($data[$k])) { $key = $k; break; } } }
  if ($key === '' || !isset($data[$key])) { return ''; }
  $v = $data[$key]; return trim(is_array($v) ? implode(', ', $v) : (string)$v);
}
function wb_sub_out($c, $s, $full) {
  $can = wb_can($c['user'], (int)$s['site_id'], 'submissions'); $st = wb_statuses(); $data = wb_arr($s['data_json']);
  $o = array('id' => (int)$s['id'], 'receipt_no' => $s['receipt_no'] ? $s['receipt_no'] : ('#' . $s['id']), 'site_id' => (int)$s['site_id'], 'site_key' => (string)$s['site_key'], 'site_name' => $s['site_name'], 'consent' => (string)$s['consent'], 'memo_preview' => $can && $s['memo'] ? wb_substr(trim(preg_replace('/\s+/', ' ', $s['memo'])), 60) : '', 'name' => $s['name'], 'phone' => wb_mask_phone($s['phone'], $can), 'tel' => $can ? 'tel:' . preg_replace('/[^0-9+]/', '', (string)$s['phone']) : '', 'visit_date' => $s['visit_date'], 'visit_time' => $s['visit_time'], 'status' => $s['status'], 'status_label' => isset($st[$s['status']]) ? $st[$s['status']] : $s['status'], 'created_at' => $s['created_at'], 'assignee' => isset($s['assignee_name']) && $s['assignee_name'] !== null ? $s['assignee_name'] : null, 'assignee_id' => $s['assignee_id'] ? (int)$s['assignee_id'] : null, 'form' => isset($s['form_name']) ? $s['form_name'] : null, 'device' => $s['device'] ? $s['device'] : null, 'page_path' => $s['page_path'], 'utm' => wb_json_safe($s['utm_json'], new stdClass()), 'has_memo' => !empty($s['memo']), 'channel' => $s['channel'] ? $s['channel'] : 'direct', 'inquiry' => wb_sub_inquiry($s, $data));
  if ($full) { if (!$can) { foreach ($data as $k => $v) { if (preg_match('/phone|tel|email/i', $k)) { $data[$k] = wb_mask_phone(is_array($v) ? implode(',', $v) : (string)$v, false); } } } $o['data'] = count($data) ? $data : new stdClass(); $o['fields'] = wb_json_safe($s['fields_json'], array()); $o['memo'] = $s['memo']; $o['referrer'] = $s['referrer']; $o['ua'] = $s['ua']; $o['retention_until'] = $s['retention_until']; $o['anonymized_at'] = $s['anonymized_at']; $o['form_version'] = $s['form_version'] === null ? null : (int)$s['form_version']; $o['updated_at'] = $s['updated_at']; $o['updated_by'] = $s['updated_by'] ? (string)wb_val('SELECT name FROM users WHERE id = ?', array((int)$s['updated_by'])) : ''; $o['advertiser_id'] = $s['advertiser_id'] ? (int)$s['advertiser_id'] : null; $o['landing_path'] = (string)$s['landing_path']; $o['consent'] = $s['consent'] ? $s['consent'] : (isset($data['agreePrivacy']) ? $data['agreePrivacy'] : (isset($data['consent']) ? $data['consent'] : '')); }
  return $o;
}
function wb_access($c, $siteId, $action, $subId = null, $detail = '') { wb_insert('submission_access_logs', array('site_id' => $siteId ? (int)$siteId : null, 'user_id' => (int)$c['user']['id'], 'submission_id' => $subId ? (int)$subId : null, 'action' => $action, 'detail' => wb_str($detail, 190), 'ip_hash' => $c['ipHash'], 'created_at' => wb_now())); }
function wb_sub_of($c, $id, $ability = null) { $s = wb_get('SELECT s.*, f.name AS form_name, u.name AS assignee_name, st.name AS site_name FROM form_submissions s JOIN forms f ON f.id = s.form_id JOIN sites st ON st.id = s.site_id LEFT JOIN users u ON u.id = s.assignee_id WHERE s.id = ? AND s.deleted_at IS NULL', array((int)$id)); if (!$s) { throw new WbHttpError(404, '예약 정보를 찾을 수 없습니다.'); } $sid = (int)$s['site_id']; if (!(wb_can($c['user'], $sid, $ability ? $ability : 'submissions.view') || wb_can($c['user'], $sid, 'submissions'))) { throw new WbHttpError(403, '권한이 없습니다.'); } if ($ability && $ability !== 'submissions.view') { wb_must($c['user'], $sid, $ability); } return $s; }
function wb_history($c, $id, $field, $before, $after) { if ((string)($before === null ? '' : $before) === (string)($after === null ? '' : $after)) { return; } wb_insert('submission_histories', array('submission_id' => (int)$id, 'user_id' => (int)$c['user']['id'], 'field' => $field, 'before_value' => $before === null ? null : wb_str($before, 2000), 'after_value' => $after === null ? null : wb_str($after, 2000), 'created_at' => wb_now())); }
function wb_anonymize($id) { wb_update('form_submissions', array('data_json' => wb_enc(array('_purged' => true)), 'name' => '(파기)', 'phone' => '', 'memo' => null, 'ua' => null, 'referrer' => null, 'anonymized_at' => wb_now(), 'updated_at' => wb_now()), 'id = ?', array((int)$id)); }
function wb_purge_expired($siteId = 0) { $rows = wb_all('SELECT id FROM form_submissions WHERE anonymized_at IS NULL AND retention_until IS NOT NULL AND retention_until < ?' . ($siteId ? ' AND site_id = ?' : ''), $siteId ? array(wb_today(), (int)$siteId) : array(wb_today())); foreach ($rows as $r) { wb_anonymize((int)$r['id']); } return count($rows); }
wb_route('GET', '/submissions', function ($c) {
  $sites = wb_sub_sites($c, wb_q($c, 'site', null)); $f = wb_sub_filters($c, $sites); $q = $c['query'];
  $page = max(1, wb_int(isset($q['page']) ? $q['page'] : 1, 1)); $per = min(200, max(5, wb_int(isset($q['per']) ? $q['per'] : 20, 20))); $sort = isset($q['sort']) && in_array($q['sort'], array('created_at', 'visit_date', 'status', 'name'), true) ? $q['sort'] : 'created_at'; $dir = isset($q['dir']) && $q['dir'] === 'asc' ? 'ASC' : 'DESC';
  $total = wb_int(wb_val('SELECT COUNT(*) FROM form_submissions s WHERE ' . $f['where'], $f['params']));
  $rows = wb_all('SELECT s.*, f.name AS form_name, u.name AS assignee_name, st.name AS site_name FROM form_submissions s JOIN forms f ON f.id = s.form_id JOIN sites st ON st.id = s.site_id LEFT JOIN users u ON u.id = s.assignee_id WHERE ' . $f['where'] . ' ORDER BY s.' . $sort . ' ' . $dir . ', s.id DESC LIMIT ' . $per . ' OFFSET ' . (($page - 1) * $per), $f['params']);
  if (count($sites)) { wb_access($c, count($sites) === 1 ? (int)$sites[0]['id'] : null, 'list', null, wb_substr(wb_enc($q), 200)); }
  $ids = wb_sub_ids($sites); $in = count($ids) ? wb_in($ids) : '0';
  $cnt = function ($w, $p = array()) use ($ids, $in) { return wb_int(wb_val('SELECT COUNT(*) FROM form_submissions WHERE site_id IN (' . $in . ') AND deleted_at IS NULL' . $w, array_merge($ids, $p))); };
  $stats = array('total' => $cnt(''), 'today' => $cnt(' AND created_at >= ?', array(wb_today() . ' 00:00:00')), 'new' => $cnt(" AND status = 'new'"), 'pending' => $cnt(" AND status IN ('new','checking')"), 'confirmed' => $cnt(" AND status = 'confirmed'"), 'month' => $cnt(' AND created_at >= ?', array(substr(wb_today(), 0, 7) . '-01 00:00:00')));
  $assignees = count($ids) ? array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all("SELECT DISTINCT u.id, u.name FROM users u WHERE u.status = 'active' AND (u.role = 'super' OR EXISTS (SELECT 1 FROM site_users su WHERE su.user_id = u.id AND su.site_id IN (" . $in . '))) ORDER BY u.name', $ids)) : array();
  $visitTimes = wb_visit_times(); if (count($sites) === 1) { $fr = wb_get("SELECT settings_json FROM forms WHERE site_id = ? AND `key` = 'reserve'", array((int)$sites[0]['id'])); $vt = $fr ? wb_prop(wb_json_safe($fr['settings_json'], null), 'visitTimes') : null; if (is_array($vt) && count($vt)) { $visitTimes = $vt; } }
  $out = array(); foreach ($rows as $r) { $out[] = wb_sub_out($c, $r, false); } $smsMap = wb_sms_summary_map(array_map(function ($o) { return $o['id']; }, $out)); foreach ($out as $i => $o) { $out[$i]['sms'] = isset($smsMap[$o['id']]) ? $smsMap[$o['id']] : null; }
  $gsMap = array(); if (function_exists('wb_gs_status_map')) { try { $gsMap = wb_gs_status_map(array_map(function ($o) { return $o['id']; }, $out)); } catch (Throwable $e) { $gsMap = array(); } } foreach ($out as $i => $o) { $out[$i]['gs'] = isset($gsMap[$o['id']]) ? $gsMap[$o['id']] : null; }
  $dupKeys = array(); foreach ($rows as $r) { $dg = preg_replace('/[^0-9]/', '', (string)$r['phone']); if (strlen($dg) >= 8) { $dupKeys[(int)$r['site_id'] . '|' . $dg] = array((int)$r['site_id'], $dg); } } $dupN = array();
  foreach ($dupKeys as $k => $v) { $dupN[$k] = wb_int(wb_val("SELECT COUNT(*) FROM form_submissions WHERE site_id = ? AND REPLACE(REPLACE(REPLACE(phone, '-', ''), ' ', ''), '.', '') = ? AND deleted_at IS NULL", array($v[0], $v[1]))); }
  foreach ($rows as $i => $r) { $k = (int)$r['site_id'] . '|' . preg_replace('/[^0-9]/', '', (string)$r['phone']); $out[$i]['dup'] = isset($dupN[$k]) ? max(0, $dupN[$k] - 1) : 0; } $canManage = true; $siteList = array(); foreach ($sites as $s) { if (!wb_can($c['user'], (int)$s['id'], 'submissions')) { $canManage = false; } $siteList[] = array('id' => (int)$s['id'], 'name' => $s['name']); }
  return array('rows' => $out, 'total' => $total, 'page' => $page, 'pages' => max(1, (int)ceil($total / $per)), 'stats' => $stats, 'statuses' => wb_statuses(), 'assignees' => $assignees, 'sites' => $siteList, 'visitTimes' => $visitTimes, 'canManage' => $canManage);
});
wb_route('GET', '/submissions/export.csv', function ($c) {
  $sites = wb_sub_sites($c, wb_q($c, 'site', null)); $okAll = count($sites) > 0; foreach ($sites as $s) { if (!wb_can($c['user'], (int)$s['id'], 'submissions.export')) { $okAll = false; } } if (!$okAll) { throw new WbHttpError(403, '다운로드 권한이 없습니다. (광고주 관리자 · 최고관리자만)'); }
  $f = wb_sub_filters($c, $sites); $one = count($sites) === 1 ? (int)$sites[0]['id'] : null; wb_access($c, $one, 'export', null, wb_substr(wb_enc($c['query']), 200));
  $rows = wb_all('SELECT s.*, f.name AS form_name, u.name AS assignee_name, st.name AS site_name FROM form_submissions s JOIN forms f ON f.id = s.form_id JOIN sites st ON st.id = s.site_id LEFT JOIN users u ON u.id = s.assignee_id WHERE ' . $f['where'] . ' ORDER BY s.id DESC LIMIT 5000', $f['params']);
  $keys = array(); foreach ($rows as $r) { foreach (array_keys(wb_arr($r['data_json'])) as $k) { $keys[$k] = true; } } $keys = array_keys($keys);
  $labels = array(); $ids = wb_sub_ids($sites); foreach (wb_all('SELECT ff.key, ff.label FROM form_fields ff JOIN forms fm ON fm.id = ff.form_id WHERE fm.site_id IN (' . (count($ids) ? wb_in($ids) : '0') . ')', $ids) as $l) { $labels[$l['key']] = $l['label']; } if (empty($labels['agreePrivacy'])) { $labels['agreePrivacy'] = '개인정보 동의'; }
  $st = wb_statuses(); $head = array('접수번호', '사이트', '사이트 식별값', '접수일시', '처리상태', '성함', '연락처', '방문 날짜', '방문 시간', '담당자'); foreach ($keys as $k) { $head[] = isset($labels[$k]) ? $labels[$k] : $k; } $head = array_merge($head, array('관리자 메모', '접속기기', '유입 페이지', '신청 페이지', '이전 페이지', 'UTM', '개인정보 삭제 예정일'));
  $out = "\xEF\xBB\xBF" . wb_csv_line($head);
  foreach ($rows as $r) { $d = wb_arr($r['data_json']); $line = array($r['receipt_no'] ? $r['receipt_no'] : $r['id'], $r['site_name'], (string)$r['site_key'], $r['created_at'], isset($st[$r['status']]) ? $st[$r['status']] : $r['status'], $r['name'], $r['phone'], $r['visit_date'], $r['visit_time'], (string)$r['assignee_name']); foreach ($keys as $k) { $line[] = isset($d[$k]) ? (is_array($d[$k]) ? implode(', ', $d[$k]) : $d[$k]) : ''; } $line = array_merge($line, array((string)$r['memo'], (string)$r['device'], $r['landing_path'] ? $r['landing_path'] : (string)$r['page_path'], (string)$r['page_path'], (string)$r['referrer'], (string)$r['utm_json'], (string)$r['retention_until'])); $out .= wb_csv_line($line); }
  wb_access($c, $one, 'export', null, 'CSV ' . count($rows) . '건'); wb_log($c, $one, 'submission.export', 'submission', null, '예약 CSV 다운로드 ' . count($rows) . '건');
  wb_send_file(200, 'text/csv; charset=utf-8', $out, '방문예약_' . str_replace('-', '', wb_today()) . '.csv'); return null;
});
wb_route('POST', '/submissions/bulk', function ($c) { $ids = array(); foreach ((array)wb_b($c, 'ids', array()) as $x) { if (wb_int($x)) { $ids[] = wb_int($x); } } if (!count($ids)) { throw new WbHttpError(422, '선택된 예약이 없습니다.'); } $rows = wb_all('SELECT id, site_id, status FROM form_submissions WHERE id IN (' . wb_in($ids) . ') AND deleted_at IS NULL', $ids); $action = wb_str(wb_b($c, 'action')); $st = wb_statuses(); $n = 0; foreach ($rows as $r) { $sid = (int)$r['site_id']; if ($action === 'delete') { wb_must($c['user'], $sid, 'delete'); wb_update('form_submissions', array('deleted_at' => wb_now()), 'id = ?', array((int)$r['id'])); $n++; } elseif (isset($st[$action])) { wb_must($c['user'], $sid, 'submissions'); if ($r['status'] !== $action) { wb_history($c, (int)$r['id'], 'status', isset($st[$r['status']]) ? $st[$r['status']] : $r['status'], $st[$action]); } wb_update('form_submissions', array('status' => $action, 'updated_at' => wb_now(), 'updated_by' => (int)$c['user']['id']), 'id = ?', array((int)$r['id'])); $n++; if ($r['status'] !== $action && function_exists('wb_gs_queue_status')) { try { wb_gs_queue_status($c, (int)$r['id']); } catch (Throwable $e) {} } } elseif ($action === 'assign') { wb_must($c['user'], $sid, 'submissions'); wb_update('form_submissions', array('assignee_id' => wb_int(wb_b($c, 'assignee_id')) ? wb_int(wb_b($c, 'assignee_id')) : null, 'updated_at' => wb_now(), 'updated_by' => (int)$c['user']['id']), 'id = ?', array((int)$r['id'])); $n++; } else { throw new WbHttpError(422, '알 수 없는 작업입니다.'); } } wb_log($c, null, 'submission.bulk', 'submission', null, '예약 ' . $n . '건 일괄 ' . $action); return array('count' => $n); });
wb_route('GET', '/submissions/:id', function ($c, $p) { $s = wb_sub_of($c, $p['id']); wb_access($c, (int)$s['site_id'], 'view', (int)$s['id']); $labels = array(); foreach ((array)wb_json_safe($s['fields_json'], array()) as $f) { $f = wb_arr($f); if (!empty($f['name'])) { $labels[$f['name']] = !empty($f['label']) ? $f['label'] : $f['name']; } } if (!count($labels)) { $sc = wb_form_schema((int)$s['form_id']); foreach ($sc['fields'] as $f) { $f = wb_arr($f); $labels[$f['name']] = $f['label']; } foreach ((array)wb_prop($sc['settings'], 'agreements', array()) as $a) { $a = wb_arr($a); if (!empty($a['name'])) { $labels[$a['name']] = isset($a['label']) ? $a['label'] : ''; } } } if (empty($labels['agreePrivacy'])) { $labels['agreePrivacy'] = '개인정보 수집 · 이용 동의'; } $o = wb_sub_out($c, $s, true); $o['labels'] = $labels; $o['history'] = wb_all('SELECT h.field, h.before_value, h.after_value, h.created_at, u.name AS user_name FROM submission_histories h LEFT JOIN users u ON u.id = h.user_id WHERE h.submission_id = ? ORDER BY h.id DESC LIMIT 50', array((int)$s['id'])); $o['access'] = wb_all('SELECT l.action, l.detail, l.created_at, u.name AS user_name FROM submission_access_logs l LEFT JOIN users u ON u.id = l.user_id WHERE l.submission_id = ? ORDER BY l.id DESC LIMIT 20', array((int)$s['id'])); $o['sms'] = wb_sms_logs_of((int)$s['id']); $smsCfg = wb_sms_cfg($c); $o['smsState'] = array('ready' => wb_sms_ready($smsCfg) === '', 'test' => in_array($smsCfg['provider'], array('log', 'fail'), true)); if (function_exists('wb_gs_detail')) { try { $o['gsheets'] = wb_gs_detail($s); } catch (Throwable $e) { $o['gsheets'] = null; } } $o['smsCanResend'] = wb_can($c['user'], (int)$s['site_id'], 'submissions'); $o['smsNoPhone'] = function_exists('wb_sms_missing_phone') ? wb_sms_missing_phone((int)$s['site_id']) : array(); return array('submission' => $o); });
wb_route('POST', '/submissions/:id/sms/resend', function ($c, $p) { $s = wb_sub_of($c, $p['id'], 'submissions'); if (!wb_rate('smsresend:' . (int)$s['id'], 5, 60)) { throw new WbHttpError(429, '잠시 후 다시 시도해 주세요.'); } $r = wb_sms_resend($c, (int)$s['site_id'], (int)$s['id']); wb_log($c, (int)$s['site_id'], 'submission.sms_resend', 'submission', (int)$s['id'], '예약 #' . $s['id'] . ' 문자 다시 보내기 · 성공 ' . $r['sent'] . ' · 실패 ' . $r['failed']); $r['sms'] = wb_sms_logs_of((int)$s['id']); return $r; });
wb_route('PATCH', '/submissions/:id', function ($c, $p) {
  $s = wb_sub_of($c, $p['id'], 'submissions'); $d = array('updated_at' => wb_now(), 'updated_by' => (int)$c['user']['id']); $changes = array(); $b = $c['body']; $st = wb_statuses();
  if (!empty($b['expect_updated_at']) && $s['updated_at'] && (string)$b['expect_updated_at'] !== (string)$s['updated_at']) { $who = $s['updated_by'] ? (string)wb_val('SELECT name FROM users WHERE id = ?', array((int)$s['updated_by'])) : ''; throw new WbHttpError(409, '다른 관리자' . ($who !== '' ? '(' . $who . ')' : '') . '가 ' . substr((string)$s['updated_at'], 5, 11) . ' 에 먼저 수정했습니다. 최신 내용을 확인한 뒤 다시 저장해 주세요.', array('conflict' => true, 'updated_at' => $s['updated_at'])); }
  if (wb_has($b, 'status') && isset($st[$b['status']]) && $b['status'] !== $s['status']) { $d['status'] = $b['status']; wb_history($c, (int)$s['id'], 'status', isset($st[$s['status']]) ? $st[$s['status']] : $s['status'], $st[$b['status']]); $changes[] = '상태 → ' . $st[$b['status']]; }
  if (wb_has($b, 'assignee_id')) { $aid = wb_int($b['assignee_id']) ? wb_int($b['assignee_id']) : null; if ($aid !== ($s['assignee_id'] ? (int)$s['assignee_id'] : null)) { $d['assignee_id'] = $aid; $name = $aid ? (string)wb_val('SELECT name FROM users WHERE id = ?', array($aid)) : '(없음)'; wb_history($c, (int)$s['id'], 'assignee', $s['assignee_name'] ? $s['assignee_name'] : '(없음)', $name); $changes[] = '담당자 → ' . $name; } }
  if (wb_has($b, 'memo')) { $memo = wb_str($b['memo'], 3000); if ($memo !== (string)$s['memo']) { $d['memo'] = $memo; wb_history($c, (int)$s['id'], 'memo', $s['memo'], $memo); $changes[] = '메모 수정'; } }
  if (count($d) > 2) { wb_update('form_submissions', $d, 'id = ?', array((int)$s['id'])); wb_access($c, (int)$s['site_id'], 'update', (int)$s['id'], implode(' · ', $changes)); wb_log($c, (int)$s['site_id'], 'submission.update', 'submission', (int)$s['id'], '예약 #' . $s['id'] . ' ' . implode(' · ', $changes)); }
  if (isset($d['status']) && function_exists('wb_gs_queue_status')) { try { wb_gs_queue_status($c, (int)$s['id']); } catch (Throwable $e) { wb_log_error('gsheets status queue: ' . $e->getMessage()); } }
  $ns = isset($d['status']) ? $d['status'] : $s['status']; return array('status' => $ns, 'status_label' => isset($st[$ns]) ? $st[$ns] : $ns, 'changes' => $changes, 'updated_at' => count($d) > 2 ? $d['updated_at'] : $s['updated_at']);
});
wb_route('DELETE', '/submissions/:id', function ($c, $p) { $s = wb_sub_of($c, $p['id'], 'delete'); wb_update('form_submissions', array('deleted_at' => wb_now()), 'id = ?', array((int)$s['id'])); wb_access($c, (int)$s['site_id'], 'delete', (int)$s['id']); wb_log($c, (int)$s['site_id'], 'submission.delete', 'submission', (int)$s['id'], '예약 #' . $s['id'] . ' 삭제'); return array(); });
wb_route('POST', '/submissions/:id/purge', function ($c, $p) { $s = wb_sub_of($c, $p['id'], 'manage'); wb_anonymize((int)$s['id']); wb_history($c, (int)$s['id'], 'purge', '개인정보 보관', '파기(익명화)'); wb_access($c, (int)$s['site_id'], 'purge', (int)$s['id']); wb_log($c, (int)$s['site_id'], 'submission.purge', 'submission', (int)$s['id'], '예약 #' . $s['id'] . ' 개인정보 파기'); return array(); });
wb_route('POST', '/sites/:id/submissions/purge-expired', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'manage'); $n = wb_purge_expired((int)$s['id']); wb_log($c, (int)$s['id'], 'submission.purge', 'submission', null, '보관기간 경과 ' . $n . '건 파기'); return array('count' => $n); });

/* ================= 미디어 ================= */
wb_route('GET', '/media', function ($c) { return wb_media_list($c, wb_current_site($c)); });
wb_route('GET', '/sites/:id/media', function ($c, $p) { return wb_media_list($c, wb_site_of($c, $p['id'])); });
wb_route('POST', '/media', function ($c) { return wb_upload_handler($c, wb_current_site($c)); });
wb_route('POST', '/sites/:id/media', function ($c, $p) { return wb_upload_handler($c, wb_site_of($c, $p['id'])); });
function wb_http_get($url, $timeout = 15) { if (function_exists('curl_init')) { $ch = curl_init($url); curl_setopt_array($ch, array(CURLOPT_RETURNTRANSFER => true, CURLOPT_TIMEOUT => $timeout, CURLOPT_FOLLOWLOCATION => true, CURLOPT_MAXREDIRS => 3, CURLOPT_USERAGENT => 'webbuilder')); $body = curl_exec($ch); $code = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE); $type = (string)curl_getinfo($ch, CURLINFO_CONTENT_TYPE); curl_close($ch); return array('ok' => $body !== false && $code >= 200 && $code < 300, 'status' => $code, 'body' => $body === false ? '' : $body, 'type' => $type); } $ctx = stream_context_create(array('http' => array('timeout' => $timeout, 'follow_location' => 1, 'user_agent' => 'webbuilder'))); $body = @file_get_contents($url, false, $ctx); $code = 0; if (isset($http_response_header[0]) && preg_match('/\s(\d{3})\s/', $http_response_header[0], $m)) { $code = (int)$m[1]; } return array('ok' => $body !== false && $code >= 200 && $code < 300, 'status' => $code, 'body' => $body === false ? '' : $body, 'type' => ''); }
wb_route('POST', '/media/import', function ($c) { $s = wb_current_site($c, 'media'); $url = wb_str(wb_b($c, 'url'), 1000); $allowed = array(); foreach (array($s['public_url'], $s['preview_url']) as $u) { $h = wb_host_of((string)$u); if ($h !== '') { $allowed[] = $h; } } if (!preg_match('#^https?://#i', $url) || !in_array(wb_host_of($url), $allowed, true)) { throw new WbHttpError(422, '등록된 공개 홈페이지 주소의 이미지만 가져올 수 있습니다.'); } $res = wb_http_get($url); if (!$res['ok']) { throw new WbHttpError(422, '이미지를 가져오지 못했습니다. (' . $res['status'] . ')'); } $tmp = tempnam(sys_get_temp_dir(), 'wbimp'); file_put_contents($tmp, $res['body']); $name = basename((string)parse_url($url, PHP_URL_PATH)); if ($name === '' || $name === '/') { $name = 'import.jpg'; } try { $m = wb_store_upload($c, $s, array('field' => 'file', 'name' => $name, 'tmp' => $tmp, 'size' => strlen($res['body']), 'type' => $res['type']), array('alt' => '')); } catch (Exception $e) { @unlink($tmp); throw $e; } @unlink($tmp); return array('media' => $m); });
wb_route('PATCH', '/media/:id', function ($c, $p) { $m = wb_media_of($c, $p['id'], 'media'); $d = array(); $b = $c['body']; if (wb_has($b, 'alt')) { $d['alt'] = wb_str($b['alt'], 190); } if (wb_has($b, 'name')) { $d['original_name'] = wb_str($b['name'], 190); } if (wb_has($b, 'folder_id')) { $d['folder_id'] = wb_int($b['folder_id']) ? wb_int($b['folder_id']) : null; } if (count($d)) { wb_update('media', $d, 'id = ?', array((int)$m['id'])); } return array('media' => wb_media_out(wb_get('SELECT * FROM media WHERE id = ?', array((int)$m['id'])), wb_media_base($c))); });
wb_route('GET', '/media/:id/usages', function ($c, $p) { return array('usages' => wb_usages_of($c, wb_media_of($c, $p['id']))); });
wb_route('DELETE', '/media/:id', function ($c, $p) {
  $m = wb_media_of($c, $p['id'], 'media'); $usages = wb_usages_of($c, $m); $live = array(); $hist = array(); foreach ($usages as $u) { if ($u['scope'] === 'live') { $live[] = $u; } else { $hist[] = $u; } }
  if (count($live)) { $names = array(); foreach (array_slice($live, 0, 3) as $u) { $names[] = $u['title']; } throw new WbHttpError(409, '사용 중인 파일은 삭제할 수 없습니다. (' . implode(', ', $names) . (count($live) > 3 ? ' 외 ' . (count($live) - 3) . '곳' : '') . ') 사용하는 곳에서 먼저 다른 파일로 바꾼 뒤 [게시]해 주세요.', array('usages' => $usages, 'reason' => 'in-use')); }
  if (count($hist) && !wb_bool(wb_q($c, 'force'))) { throw new WbHttpError(409, '이전 게시본 · 이전 버전에서 사용한 파일입니다. 삭제하면 그 버전으로 복원했을 때 이미지가 비어 보입니다.', array('usages' => $usages, 'reason' => 'history')); }
  wb_update('media', array('deleted_at' => wb_now()), 'id = ?', array((int)$m['id'])); $v = wb_arr($m['variants_json']);
  foreach (array_merge(array($m['filename']), array_values($v)) as $rel) { $f = wb_safe_join(wb_uploads_dir(), (string)$rel); if ($f && is_file($f)) { @unlink($f); } }
  wb_log($c, (int)$m['site_id'], 'media.delete', 'media', (int)$m['id'], '파일 삭제 ' . $m['original_name'] . (count($hist) ? ' (이전 버전에서만 사용)' : '')); return array();
});
wb_route('POST', '/media/:id/replace', function ($c, $p) { $m = wb_media_of($c, $p['id'], 'media'); $f = null; foreach ($c['files'] as $x) { if (preg_match('/^files?$/', $x['field'])) { $f = $x; break; } } if (!$f) { throw new WbHttpError(422, '파일이 없습니다.'); } $data = (string)@file_get_contents($f['tmp']); $sn = wb_sniff($data); $allowed = wb_allowed_types(); if (!$sn || !isset($allowed[$sn['ext']])) { throw new WbHttpError(422, '허용되지 않는 파일 형식입니다.'); } $v = wb_arr($m['variants_json']); $target = wb_safe_join(wb_uploads_dir(), !empty($v['src']) ? $v['src'] : $m['filename']); if (!$target || @file_put_contents($target, $data, LOCK_EX) === false) { throw new WbHttpError(500, '파일을 저장할 수 없습니다. assets/uploads 폴더 권한을 확인해 주세요.'); } $size = strpos($sn['mime'], 'image/') === 0 && $sn['ext'] !== 'svg' ? wb_image_size($target, $sn['ext']) : array(null, null); $tf = wb_file_by_field($c, 'thumb_0'); if ($tf && !empty($v['thumb'])) { @file_put_contents(wb_safe_join(wb_uploads_dir(), $v['thumb']), file_get_contents($tf['tmp']), LOCK_EX); } $mf = wb_file_by_field($c, 'mobile_0'); if ($mf && !empty($v['mobile'])) { @file_put_contents(wb_safe_join(wb_uploads_dir(), $v['mobile']), file_get_contents($mf['tmp']), LOCK_EX); } wb_update('media', array('size' => strlen($data), 'width' => $size[0], 'height' => $size[1], 'hash' => wb_sha256($data), 'mime' => $sn['mime']), 'id = ?', array((int)$m['id'])); wb_log($c, (int)$m['site_id'], 'media.replace', 'media', (int)$m['id'], '파일 교체 ' . $m['original_name']); return array('media' => wb_media_out(wb_get('SELECT * FROM media WHERE id = ?', array((int)$m['id'])), wb_media_base($c))); });

/* ================= 팝업 ================= */
function wb_popup_out($p, $base) { $n = wb_now(); return array('id' => (int)$p['id'], 'name' => $p['name'], 'type' => $p['type'], 'pc_media_id' => $p['pc_media_id'] ? (int)$p['pc_media_id'] : null, 'mobile_media_id' => $p['mobile_media_id'] ? (int)$p['mobile_media_id'] : null, 'video_media_id' => $p['video_media_id'] ? (int)$p['video_media_id'] : null, 'poster_media_id' => $p['poster_media_id'] ? (int)$p['poster_media_id'] : null, 'pc_src' => $p['pc_media_id'] ? wb_media_by_id((int)$p['pc_media_id'], $base) : (string)$p['pc_src'], 'mobile_src' => $p['mobile_media_id'] ? wb_media_by_id((int)$p['mobile_media_id'], $base, 'mobile') : (string)$p['mobile_src'], 'video_url' => $p['video_media_id'] ? wb_media_by_id((int)$p['video_media_id'], $base) : (string)$p['video_url'], 'poster_src' => $p['poster_media_id'] ? wb_media_by_id((int)$p['poster_media_id'], $base) : '', 'alt' => (string)$p['alt'], 'link' => (string)$p['link'], 'target' => $p['target'] ? $p['target'] : '_self', 'pages' => wb_json_safe($p['pages_json'], array('main')), 'position' => wb_json_safe($p['position_json'], new stdClass()), 'size' => wb_json_safe($p['size_json'], new stdClass()), 'sort' => (int)$p['sort'], 'start_at' => $p['start_at'], 'end_at' => $p['end_at'], 'status' => $p['status'], 'hide_rule' => $p['hide_rule'] ? $p['hide_rule'] : 'today', 'reshow_hours' => $p['reshow_hours'] === null ? null : (int)$p['reshow_hours'], 'devices' => $p['devices'] ? $p['devices'] : 'all', 'priority' => (int)$p['priority'], 'overlay' => $p['overlay'] === null ? null : (float)$p['overlay'], 'options' => wb_json_safe($p['options_json'], new stdClass()), 'impressions' => (int)$p['impressions'], 'clicks' => (int)$p['clicks'], 'created_at' => $p['created_at'], 'updated_at' => $p['updated_at'], 'active' => $p['status'] === 'published' && (!$p['start_at'] || $p['start_at'] <= $n) && (!$p['end_at'] || $p['end_at'] >= $n)); }
function wb_popup_input($c) { $b = $c['body']; $d = array(); foreach (array('name', 'alt', 'link') as $k) { if (wb_has($b, $k)) { $d[$k] = wb_str($b[$k], $k === 'link' ? 500 : 120); } } if (!empty($b['type'])) { $d['type'] = $b['type'] === 'video' ? 'video' : 'image'; } if (!empty($b['target'])) { $d['target'] = $b['target'] === '_blank' ? '_blank' : '_self'; } foreach (array('pc_media_id', 'mobile_media_id', 'video_media_id', 'poster_media_id') as $k) { if (wb_has($b, $k)) { $d[$k] = wb_int($b[$k]) ? wb_int($b[$k]) : null; } } foreach (array('pc_src', 'mobile_src', 'video_url') as $k) { if (wb_has($b, $k)) { $d[$k] = wb_str($b[$k], 500); } } if (wb_has($b, 'pages')) { $pg = array(); if (is_array($b['pages'])) { foreach ($b['pages'] as $x) { $pg[] = (string)$x; } } $d['pages_json'] = wb_enc(count($pg) ? $pg : array('main')); } if (wb_has($b, 'position')) { $d['position_json'] = wb_enc(wb_bo($c, 'position', new stdClass())); } if (wb_has($b, 'size')) { $d['size_json'] = wb_enc(wb_bo($c, 'size', new stdClass())); } if (wb_has($b, 'start_at')) { $d['start_at'] = $b['start_at'] ? str_replace('T', ' ', wb_str($b['start_at'], 19)) : null; } if (wb_has($b, 'end_at')) { $d['end_at'] = $b['end_at'] ? str_replace('T', ' ', wb_str($b['end_at'], 19)) : null; } if (!empty($b['status']) && in_array($b['status'], array('draft', 'published', 'stopped'), true)) { $d['status'] = $b['status']; } if (!empty($b['hide_rule']) && in_array($b['hide_rule'], array('always', 'session', 'today', 'daily'), true)) { $d['hide_rule'] = $b['hide_rule']; } if (!empty($b['devices']) && in_array($b['devices'], array('all', 'pc', 'mobile'), true)) { $d['devices'] = $b['devices']; } if (wb_has($b, 'priority')) { $d['priority'] = wb_int($b['priority']); } if (wb_has($b, 'overlay')) { $d['overlay'] = ($b['overlay'] === '' || $b['overlay'] === null) ? null : max(0, min(1, (float)$b['overlay'])); } if (wb_has($b, 'options')) { $d['options_json'] = wb_enc(wb_bo($c, 'options', new stdClass())); } return $d; }
function wb_popup_of($c, $id) { $p = wb_get("SELECT * FROM popups WHERE id = ? AND status <> 'deleted'", array((int)$id)); if (!$p) { throw new WbHttpError(404, '팝업을 찾을 수 없습니다.'); } wb_site_of($c, (int)$p['site_id'], 'manage'); return $p; }
wb_route('GET', '/sites/:id/popups', function ($c, $p) { $s = wb_site_of($c, $p['id']); $base = wb_media_base($c); $out = array(); foreach (wb_all("SELECT * FROM popups WHERE site_id = ? AND status <> 'deleted' ORDER BY priority DESC, sort, id", array((int)$s['id'])) as $x) { $out[] = wb_popup_out($x, $base); } return array('popups' => $out, 'pages' => wb_all('SELECT `key`, title FROM pages WHERE site_id = ? AND deleted_at IS NULL ORDER BY sort', array((int)$s['id']))); });
wb_route('POST', '/sites/:id/popups', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'manage'); $d = wb_popup_input($c); if (empty($d['name'])) { throw new WbHttpError(422, '관리용 제목을 입력해 주세요.'); } $d = array_merge(array('status' => 'draft', 'hide_rule' => 'today', 'devices' => 'all', 'priority' => 0, 'pages_json' => wb_enc(array('main')), 'position_json' => '{}', 'size_json' => '{}', 'options_json' => '{}', 'type' => 'image', 'target' => '_self'), $d, array('site_id' => (int)$s['id'], 'sort' => wb_int(wb_val('SELECT COALESCE(MAX(sort), 0) + 1 FROM popups WHERE site_id = ?', array((int)$s['id']))), 'reshow_hours' => 24, 'created_by' => (int)$c['user']['id'], 'created_at' => wb_now(), 'updated_at' => wb_now())); $id = wb_insert('popups', $d); wb_log($c, (int)$s['id'], 'popup.create', 'popup', $id, '팝업 등록 ' . $d['name']); return array('popup' => wb_popup_out(wb_get('SELECT * FROM popups WHERE id = ?', array($id)), wb_media_base($c))); });
wb_route('PUT', '/popups/:id', function ($c, $p) { $pp = wb_popup_of($c, $p['id']); $d = wb_popup_input($c); $d['updated_at'] = wb_now(); wb_update('popups', $d, 'id = ?', array((int)$pp['id'])); wb_log($c, (int)$pp['site_id'], 'popup.update', 'popup', (int)$pp['id'], '팝업 수정 ' . (!empty($d['name']) ? $d['name'] : $pp['name'])); return array('popup' => wb_popup_out(wb_get('SELECT * FROM popups WHERE id = ?', array((int)$pp['id'])), wb_media_base($c))); });
wb_route('DELETE', '/popups/:id', function ($c, $p) { $pp = wb_popup_of($c, $p['id']); wb_update('popups', array('status' => 'deleted', 'updated_at' => wb_now()), 'id = ?', array((int)$pp['id'])); wb_log($c, (int)$pp['site_id'], 'popup.delete', 'popup', (int)$pp['id'], '팝업 삭제 ' . $pp['name']); return array(); });
wb_route('POST', '/sites/:id/popups/reorder', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'manage'); $i = 0; foreach ((array)wb_b($c, 'ids', array()) as $id) { wb_update('popups', array('sort' => $i++), 'id = ? AND site_id = ?', array(wb_int($id), (int)$s['id'])); } return array(); });

/* ================= SEO (최종 제목 · 설명 계산과 sitemap 미리보기는 관리자 화면이 공유 코어(WBCore)로 계산) ================= */
function wb_seo_row($r) { if (!$r) { return array('title' => '', 'description' => '', 'keywords' => '', 'canonical' => '', 'robots' => 'index,follow', 'og' => new stdClass(), 'structured' => null, 'verification' => new stdClass(), 'favicon_media_id' => null, 'share_image_media_id' => null, 'mode' => '', 'title_rule' => 'page_site', 'noindex' => false); } $og = wb_json_safe($r['og_json'], new stdClass()); if (is_object($og) && isset($og->image) && is_string($og->image) && preg_match('#^https?://(www\.)?example\.com/#i', $og->image)) { $og->image = preg_replace('#^https?://(www\.)?example\.com/#i', './', $og->image); } return array('title' => (string)$r['title'], 'description' => (string)$r['description'], 'keywords' => (string)$r['keywords'], 'canonical' => (string)$r['canonical'], 'robots' => $r['robots'] ? $r['robots'] : 'index,follow', 'og' => is_object($og) ? $og : new stdClass(), 'structured' => wb_json_safe($r['structured_json'], null), 'verification' => wb_json_safe($r['verification_json'], new stdClass()), 'favicon_media_id' => $r['favicon_media_id'] ? (int)$r['favicon_media_id'] : null, 'share_image_media_id' => $r['share_image_media_id'] ? (int)$r['share_image_media_id'] : null, 'mode' => (string)$r['mode'], 'title_rule' => $r['title_rule'] ? $r['title_rule'] : 'page_site', 'noindex' => (int)$r['noindex'] === 1); }
function wb_seo_input($c) { $b = $c['body']; $d = array('updated_at' => wb_now()); foreach (array('title', 'description', 'keywords', 'canonical', 'robots') as $k) { if (wb_has($b, $k)) { $d[$k] = wb_str($b[$k], $k === 'description' ? 500 : ($k === 'keywords' ? 250 : 190)); } } if (!empty($d['canonical']) && preg_match('#^https?://(localhost|127\.0\.0\.1|(www\.)?example\.com)#i', $d['canonical'])) { throw new WbHttpError(422, '대표 주소(canonical)에는 실제 공개 도메인을 입력해 주세요. (localhost · example.com 은 사용할 수 없습니다)'); } if (wb_has($b, 'og')) { $d['og_json'] = wb_enc(wb_bo($c, 'og', new stdClass())); } if (wb_has($b, 'structured')) { $d['structured_json'] = wb_enc(wb_bo($c, 'structured')); } if (wb_has($b, 'verification')) { $d['verification_json'] = wb_enc(wb_bo($c, 'verification', new stdClass())); } if (wb_has($b, 'favicon_media_id')) { $d['favicon_media_id'] = wb_int($b['favicon_media_id']) ? wb_int($b['favicon_media_id']) : null; } if (wb_has($b, 'share_image_media_id')) { $d['share_image_media_id'] = wb_int($b['share_image_media_id']) ? wb_int($b['share_image_media_id']) : null; } if (wb_has($b, 'mode')) { $d['mode'] = in_array($b['mode'], array('inherit', 'auto', 'custom'), true) ? $b['mode'] : null; } if (wb_has($b, 'title_rule')) { $d['title_rule'] = in_array($b['title_rule'], array('page_site', 'site_page', 'site'), true) ? $b['title_rule'] : 'page_site'; } if (wb_has($b, 'noindex')) { $d['noindex'] = wb_bool($b['noindex']) ? 1 : 0; } return $d; }
wb_route('GET', '/sites/:id/seo', function ($c, $p) { $s = wb_site_of($c, $p['id']); $base = wb_media_base($c); $site = wb_get("SELECT * FROM seo WHERE site_id = ? AND scope = 'site'", array((int)$s['id'])); $pages = array(); foreach (wb_all('SELECT id, `key`, type, title, status, updated_at FROM pages WHERE site_id = ? AND deleted_at IS NULL ORDER BY sort', array((int)$s['id'])) as $pg) { $pg = wb_ints($pg, array('id')); $row = wb_get("SELECT * FROM seo WHERE site_id = ? AND scope = 'page' AND page_id = ?", array((int)$s['id'], (int)$pg['id'])); $pg['seo'] = wb_seo_row($row); $pg['image'] = $row && $row['share_image_media_id'] ? wb_media_by_id((int)$row['share_image_media_id'], $base) : ''; $pg['resolved'] = new stdClass(); $pg['mode'] = $row && $row['mode'] ? $row['mode'] : 'inherit'; $pg['path'] = $pg['type'] === 'main' ? '/' : '/index.html#page=' . $pg['key']; $pages[] = $pg; } $pub = wb_site_url($s); return array('site' => wb_seo_row($site), 'favicon' => $site && $site['favicon_media_id'] ? wb_media_by_id((int)$site['favicon_media_id'], $base) : '', 'shareImage' => $site && $site['share_image_media_id'] ? wb_media_by_id((int)$site['share_image_media_id'], $base) : '', 'pages' => $pages, 'resolved' => new stdClass(), 'clientResolve' => true, 'publicUrl' => $pub, 'domainOk' => preg_match('#^https?://#', $pub) === 1 && !preg_match('/localhost|127\.0\.0\.1|example\.com/i', $pub), 'sitemap' => $pub ? $pub . '/sitemap.xml' : '', 'robotsUrl' => $pub ? $pub . '/robots.txt' : '', 'sitemapPreview' => '', 'robotsPreview' => '', 'ftp' => false); });
wb_route('PUT', '/sites/:id/seo', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'manage'); $d = wb_seo_input($c); $row = wb_get("SELECT id FROM seo WHERE site_id = ? AND scope = 'site'", array((int)$s['id'])); if ($row) { wb_update('seo', $d, 'id = ?', array((int)$row['id'])); } else { wb_insert('seo', array_merge($d, array('site_id' => (int)$s['id'], 'scope' => 'site', 'page_id' => null))); } wb_log($c, (int)$s['id'], 'seo.update', 'seo', null, '사이트 SEO 수정'); return array(); });
wb_route('GET', '/pages/:id/seo', function ($c, $p) { $pg = wb_page_of($c, $p['id']); return array('seo' => wb_seo_row(wb_get("SELECT * FROM seo WHERE site_id = ? AND scope = 'page' AND page_id = ?", array((int)$pg['site_id'], (int)$pg['id']))), 'page' => wb_page_row($pg)); });
wb_route('PUT', '/pages/:id/seo', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'manage'); $d = wb_seo_input($c); $row = wb_get("SELECT id FROM seo WHERE site_id = ? AND scope = 'page' AND page_id = ?", array((int)$pg['site_id'], (int)$pg['id'])); if ($row) { wb_update('seo', $d, 'id = ?', array((int)$row['id'])); } else { wb_insert('seo', array_merge($d, array('site_id' => (int)$pg['site_id'], 'scope' => 'page', 'page_id' => (int)$pg['id']))); } wb_log($c, (int)$pg['site_id'], 'seo.update', 'seo', (int)$pg['id'], '페이지 SEO 수정 ' . $pg['title']); return array(); });

/* ================= 통계 ================= */
wb_route('GET', '/sites/:id/analytics', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'stats'); $to = preg_match('/^\d{4}-\d{2}-\d{2}$/', wb_q($c, 'to')) ? wb_q($c, 'to') : wb_today(); $from = preg_match('/^\d{4}-\d{2}-\d{2}$/', wb_q($c, 'from')) ? wb_q($c, 'from') : wb_today(wb_days(-29, strtotime($to . ' 00:00:00'))); if ($from > $to) { $from = $to; } $days = (int)round((strtotime($to . ' 00:00:00') - strtotime($from . ' 00:00:00')) / 86400) + 1; $prevTo = wb_today(wb_days(-1, strtotime($from . ' 00:00:00'))); $prevFrom = wb_today(wb_days(-$days, strtotime($from . ' 00:00:00'))); return array('from' => $from, 'to' => $to, 'report' => wb_report((int)$s['id'], $from, $to), 'prev' => wb_report((int)$s['id'], $prevFrom, $prevTo), 'popups' => array_map(function ($r) { return wb_ints($r, array('id', 'impressions', 'clicks')); }, wb_all("SELECT id, name, type, impressions, clicks FROM popups WHERE site_id = ? AND status <> 'deleted' ORDER BY impressions DESC LIMIT 20", array((int)$s['id']))), 'analytics' => wb_get_setting((int)$s['id'], 'analytics')); });

/* ================= 계정 · 권한 (최고관리자) ================= */
function wb_user_out($u) { $o = wb_public_user($u); $o['login_fails'] = (int)(isset($u['failed_logins']) ? $u['failed_logins'] : 0); $o['locked'] = !empty($u['locked_until']) && $u['locked_until'] > wb_now(); $o['locked_until'] = !empty($u['locked_until']) ? $u['locked_until'] : null; $o['sites'] = array_map(function ($r) { return wb_ints($r, array('site_id')); }, wb_all('SELECT su.site_id, su.role, s.name FROM site_users su JOIN sites s ON s.id = su.site_id WHERE su.user_id = ?', array((int)$u['id']))); $o['advertisers'] = array_map(function ($r) { return wb_ints($r, array('advertiser_id')); }, wb_all('SELECT ua.advertiser_id, ua.role, a.name FROM user_advertisers ua JOIN advertisers a ON a.id = ua.advertiser_id WHERE ua.user_id = ?', array((int)$u['id']))); return $o; }
function wb_set_user_advertisers($uid, $list) { if (!is_array($list)) { return; } wb_del('user_advertisers', 'user_id = ?', array((int)$uid)); foreach ($list as $a) { $aid = is_array($a) ? wb_int(isset($a['advertiser_id']) ? $a['advertiser_id'] : 0) : wb_int($a); if (!$aid) { continue; } $role = is_array($a) && isset($a['role']) && in_array($a['role'], wb_site_roles(), true) ? $a['role'] : 'staff'; wb_insert('user_advertisers', array('advertiser_id' => $aid, 'user_id' => (int)$uid, 'role' => $role, 'created_at' => wb_now())); } }
function wb_set_user_sites($uid, $list) { wb_del('site_users', 'user_id = ?', array((int)$uid)); foreach ((array)$list as $s) { $sid = is_array($s) ? wb_int(isset($s['site_id']) ? $s['site_id'] : 0) : wb_int($s); if (!$sid) { continue; } $role = is_array($s) && isset($s['role']) && in_array($s['role'], wb_site_roles(), true) ? $s['role'] : 'editor'; wb_insert('site_users', array('site_id' => $sid, 'user_id' => (int)$uid, 'role' => $role, 'can_publish' => 1, 'created_at' => wb_now())); } }
/* 문자 수신을 켜려면 올바른 휴대전화번호가 있어야 함 (저장될 최종 값 기준) */
function wb_user_sms_check($d, $old) { $on = isset($d['sms_notify']) ? (int)$d['sms_notify'] : ($old ? (int)$old['sms_notify'] : 0); $ph = isset($d['phone']) ? $d['phone'] : ($old ? (string)$old['phone'] : ''); if ($on && trim((string)$ph) !== '' && wb_sms_mobile($ph) === '') { throw new WbHttpError(422, '방문예약 문자를 받으려면 휴대전화번호(010-1234-5678 형식)를 입력해 주세요.'); } }   /* 비워 두면 저장은 되고 문자만 안 감 (화면에 "문자 수신번호가 등록되지 않았습니다." 안내) */
function wb_user_input($b, $isNew) { $d = array(); $roles = wb_roles(); if (wb_has($b, 'login_id')) { $id = wb_lower(trim(wb_str($b['login_id']))); if (!preg_match('/^[a-z0-9_.@\-]{3,40}$/', $id)) { throw new WbHttpError(422, '로그인 아이디는 영문 · 숫자 3~40자입니다.'); } $d['login_id'] = $id; } foreach (array('name', 'email', 'phone', 'company', 'tel') as $k) { if (wb_has($b, $k)) { $d[$k] = trim(wb_str($b[$k], 120)); } } if (isset($d['email'])) { $d['email'] = wb_lower($d['email']); } if (wb_has($b, 'role')) { if (!isset($roles[$b['role']])) { throw new WbHttpError(422, '권한 그룹이 올바르지 않습니다.'); } $d['role'] = $b['role']; } if (wb_has($b, 'status')) { $d['status'] = in_array($b['status'], array('active', 'inactive'), true) ? $b['status'] : 'active'; } if (!empty($b['password'])) { $err = wb_valid_password($b['password']); if ($err) { throw new WbHttpError(422, $err); } $d['password_hash'] = wb_hash_password($b['password']); $d['must_change_password'] = 0; } if (isset($d['phone']) && $d['phone'] !== '') { $m = wb_sms_mobile($d['phone']); if ($m === '') { throw new WbHttpError(422, '휴대전화번호 형식이 올바르지 않습니다. (예 : 010-1234-5678)'); } $d['phone'] = wb_sms_pretty($m); } if (wb_has($b, 'sms_notify')) { $d['sms_notify'] = wb_bool($b['sms_notify']) ? 1 : 0; } if ($isNew && empty($d['login_id'])) { throw new WbHttpError(422, '로그인 아이디를 입력해 주세요.'); } if ($isNew && empty($d['password_hash'])) { throw new WbHttpError(422, '초기 비밀번호를 입력해 주세요.'); } return $d; }
wb_route('GET', '/users', function ($c) { wb_must_super($c['user']); $adv = array(); foreach (wb_advertisers($c['user']) as $a) { $adv[] = array('id' => (int)$a['id'], 'name' => $a['name']); } return array('advertisers' => $adv, 'siteRoles' => wb_site_roles(), 'users' => array_map('wb_user_out', wb_all('SELECT * FROM users ORDER BY id')), 'roles' => wb_roles(), 'sites' => array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all("SELECT id, name, `key` FROM sites WHERE status <> 'deleted' ORDER BY id"))); });
wb_route('POST', '/users', function ($c) { wb_must_super($c['user']); $d = wb_user_input($c['body'], true); if (!isset($d['sms_notify'])) { $d['sms_notify'] = 1; }   /* 새 계정 : 방문예약 문자 수신 기본 ON (기존 계정 값은 바꾸지 않음) */ wb_user_sms_check($d, null); $email = !empty($d['email']) ? $d['email'] : $d['login_id']; if (wb_get('SELECT id FROM users WHERE LOWER(login_id) = ? OR LOWER(email) = ?', array($d['login_id'], $email))) { throw new WbHttpError(422, '이미 사용 중인 아이디 또는 이메일입니다.'); } if (empty($d['email'])) { $d['email'] = strpos($d['login_id'], '@') !== false ? $d['login_id'] : $d['login_id'] . '@local'; } $d['created_at'] = wb_now(); $d['updated_at'] = wb_now(); if (empty($d['role'])) { $d['role'] = 'editor'; } if (empty($d['status'])) { $d['status'] = 'active'; } if (!isset($d['name']) || $d['name'] === '') { $d['name'] = $d['login_id']; } $id = wb_insert('users', $d); wb_set_user_sites($id, wb_b($c, 'sites', array())); wb_set_user_advertisers($id, wb_b($c, 'advertisers')); $roles = wb_roles(); wb_log($c, null, 'user.create', 'user', $id, '계정 생성 ' . $d['login_id'] . ' (' . $roles[$d['role']] . ')'); return array('user' => wb_user_out(wb_get('SELECT * FROM users WHERE id = ?', array($id)))); });
wb_route('PUT', '/users/:id', function ($c, $p) { wb_must_super($c['user']); $u = wb_get('SELECT * FROM users WHERE id = ?', array((int)$p['id'])); if (!$u) { throw new WbHttpError(404, '계정을 찾을 수 없습니다.'); } $d = wb_user_input($c['body'], false); wb_user_sms_check($d, $u); $me = (int)$u['id'] === (int)$c['user']['id']; if ($me && ((!empty($d['role']) && $d['role'] !== 'super') || (isset($d['status']) && $d['status'] === 'inactive'))) { throw new WbHttpError(422, '자신의 권한이나 상태는 변경할 수 없습니다.'); } if (!empty($d['login_id']) && wb_get('SELECT id FROM users WHERE LOWER(login_id) = ? AND id <> ?', array($d['login_id'], (int)$u['id']))) { throw new WbHttpError(422, '이미 사용 중인 아이디입니다.'); } $d['updated_at'] = wb_now(); wb_update('users', $d, 'id = ?', array((int)$u['id'])); if (wb_has($c['body'], 'sites')) { wb_set_user_sites((int)$u['id'], wb_b($c, 'sites', array())); } if (wb_has($c['body'], 'advertisers')) { wb_set_user_advertisers((int)$u['id'], wb_b($c, 'advertisers')); } $newToken = null; if ((isset($d['status']) && $d['status'] === 'inactive') || !empty($d['password_hash'])) { wb_logout_all((int)$u['id']); if ($me && !empty($d['password_hash'])) { $newToken = wb_create_session((int)$u['id'], $c); } } wb_log($c, null, 'user.update', 'user', (int)$u['id'], '계정 수정 ' . (!empty($d['login_id']) ? $d['login_id'] : $u['login_id']), null, array_keys($d)); $out = array('user' => wb_user_out(wb_get('SELECT * FROM users WHERE id = ?', array((int)$u['id'])))); if ($newToken) { $out['token'] = $newToken; } return $out; });
wb_route('DELETE', '/users/:id', function ($c, $p) { wb_must_super($c['user']); $u = wb_get('SELECT * FROM users WHERE id = ?', array((int)$p['id'])); if (!$u) { throw new WbHttpError(404, '계정을 찾을 수 없습니다.'); } if ((int)$u['id'] === (int)$c['user']['id']) { throw new WbHttpError(422, '자신의 계정은 삭제할 수 없습니다.'); } if ($u['role'] === 'super' && wb_int(wb_val("SELECT COUNT(*) FROM users WHERE role = 'super' AND status = 'active'")) <= 1) { throw new WbHttpError(422, '마지막 최고관리자는 삭제할 수 없습니다.'); } $t = time(); wb_update('users', array('status' => 'inactive', 'updated_at' => wb_now(), 'login_id' => $u['login_id'] . '.deleted.' . $t, 'email' => $u['email'] . '.deleted.' . $t), 'id = ?', array((int)$u['id'])); wb_logout_all((int)$u['id']); wb_del('site_users', 'user_id = ?', array((int)$u['id'])); wb_del('user_advertisers', 'user_id = ?', array((int)$u['id'])); wb_log($c, null, 'user.delete', 'user', (int)$u['id'], '계정 삭제 ' . $u['login_id']); return array(); });
wb_route('POST', '/users/:id/unlock', function ($c, $p) { wb_must_super($c['user']); $u = wb_get('SELECT * FROM users WHERE id = ?', array((int)$p['id'])); if (!$u) { throw new WbHttpError(404, '계정을 찾을 수 없습니다.'); } wb_update('users', array('failed_logins' => 0, 'locked_until' => null, 'updated_at' => wb_now()), 'id = ?', array((int)$u['id'])); wb_log($c, null, 'user.unlock', 'user', (int)$u['id'], '계정 잠금 해제 ' . $u['login_id']); return array('user' => wb_user_out(wb_get('SELECT * FROM users WHERE id = ?', array((int)$u['id'])))); });
wb_route('POST', '/users/:id/logout-all', function ($c, $p) { wb_must_super($c['user']); return array('count' => wb_logout_all((int)$p['id'])); });

/* ================= 로그 · 검색 ================= */
wb_route('GET', '/logs/logins', function ($c) { wb_must_super($c['user']); return array('rows' => array_map(function ($r) { return wb_ints($r, array('id', 'user_id', 'success')); }, wb_all('SELECT l.*, u.name AS user_name FROM login_logs l LEFT JOIN users u ON u.id = l.user_id ORDER BY l.id DESC LIMIT 100'))); });
wb_route('GET', '/sites/:id/logs', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'logs'); $page = max(1, wb_int(wb_q($c, 'page', 1), 1)); $per = 30; $where = array((wb_q($c, 'global') === '1' && wb_is_super($c['user'])) ? '(l.site_id = ? OR l.site_id IS NULL)' : 'l.site_id = ?'); $params = array((int)$s['id']); if (wb_q($c, 'q') !== '') { $where[] = '(l.summary LIKE ? OR l.action LIKE ?)'; $params[] = '%' . wb_q($c, 'q') . '%'; $params[] = '%' . wb_q($c, 'q') . '%'; } $w = implode(' AND ', $where); $total = wb_int(wb_val('SELECT COUNT(*) FROM activity_logs l WHERE ' . $w, $params)); return array('rows' => array_map(function ($r) { return wb_ints($r, array('id', 'target_id')); }, wb_all('SELECT l.id, l.action, l.target_type, l.target_id, l.summary, l.created_at, u.name AS user_name FROM activity_logs l LEFT JOIN users u ON u.id = l.user_id WHERE ' . $w . ' ORDER BY l.id DESC LIMIT ' . $per . ' OFFSET ' . (($page - 1) * $per), $params)), 'total' => $total, 'page' => $page, 'pages' => max(1, (int)ceil($total / $per)), 'access' => wb_can($c['user'], (int)$s['id'], 'submissions') ? array_map(function ($r) { return wb_ints($r, array('submission_id')); }, wb_all('SELECT l.action, l.detail, l.submission_id, l.created_at, u.name AS user_name FROM submission_access_logs l LEFT JOIN users u ON u.id = l.user_id WHERE l.site_id = ? ORDER BY l.id DESC LIMIT 30', array((int)$s['id']))) : array()); });
wb_route('GET', '/logs/:id', function ($c, $p) { $l = wb_get('SELECT * FROM activity_logs WHERE id = ?', array((int)$p['id'])); if (!$l) { throw new WbHttpError(404, '없음'); } if (!empty($l['site_id'])) { wb_site_of($c, (int)$l['site_id'], 'logs'); } else { wb_must_super($c['user']); } $l = wb_ints($l, array('id', 'site_id', 'user_id', 'target_id')); $l['before'] = wb_json_safe($l['before_json'], null); $l['after'] = wb_json_safe($l['after_json'], null); return array('log' => $l); });
wb_route('GET', '/sites/:id/search', function ($c, $p) { $s = wb_site_of($c, $p['id']); $q = trim(wb_q($c, 'q')); if ($q === '') { return array('results' => array()); } $like = '%' . $q . '%'; $results = array(); foreach (wb_all('SELECT id, `key`, title FROM pages WHERE site_id = ? AND deleted_at IS NULL AND (title LIKE ? OR `key` LIKE ?) LIMIT 10', array((int)$s['id'], $like, $like)) as $r) { $results[] = array('type' => 'page', 'id' => (int)$r['id'], 'title' => $r['title'], 'hint' => $r['key']); } if (wb_can($c['user'], (int)$s['id'], 'media')) { foreach (wb_all('SELECT id, original_name FROM media WHERE site_id = ? AND deleted_at IS NULL AND (original_name LIKE ? OR alt LIKE ?) LIMIT 10', array((int)$s['id'], $like, $like)) as $r) { $results[] = array('type' => 'media', 'id' => (int)$r['id'], 'title' => $r['original_name']); } } if (wb_can($c['user'], (int)$s['id'], 'submissions')) { foreach (wb_all('SELECT id, name, phone, created_at FROM form_submissions WHERE site_id = ? AND deleted_at IS NULL AND (name LIKE ? OR phone LIKE ?) ORDER BY id DESC LIMIT 10', array((int)$s['id'], $like, $like)) as $r) { $results[] = array('type' => 'submission', 'id' => (int)$r['id'], 'title' => $r['name'] . ' · ' . $r['phone'], 'hint' => $r['created_at']); } } return array('results' => $results); });

/* ================= 시스템 (최고관리자) : 백업은 DB 전체를 JSON 으로 api/data/backups/ 에 저장 (파일명 .php + 첫 줄 exit 로 웹에서 직접 열어도 내용이 보이지 않음) ================= */
function wb_backup_tables() { return array('advertisers', 'users', 'user_advertisers', 'sites', 'site_users', 'settings', 'menus', 'menu_items', 'section_types', 'pages', 'page_versions', 'forms', 'form_fields', 'form_submissions', 'submission_histories', 'sms_logs', 'submission_access_logs', 'media_folders', 'media', 'popups', 'seo', 'publish_snapshots', 'analytics_daily', 'activity_logs', 'login_logs', 'system_settings'); }
function wb_make_backup($c, $label = '') { $dir = WB_DATA_DIR . '/backups'; if (!is_dir($dir)) { @mkdir($dir, 0755, true); } $stamp = date('Ymd-His'); $name = 'backup-' . $stamp . ($label !== '' ? '-' . preg_replace('/[^a-z0-9\-]/', '', wb_slugify($label)) : '') . '.php'; $tables = array(); foreach (wb_backup_tables() as $t) { $tables[$t] = wb_all('SELECT * FROM `' . $t . '`'); } $json = wb_enc(array('created_at' => wb_now(), 'version' => WB_VERSION, 'schema' => WB_SCHEMA_VERSION, 'sites' => wb_all('SELECT `key`, name FROM sites'), 'tables' => $tables)); $text = "<?php exit; ?>\n" . $json; if (!wb_write_atomic($dir . '/' . $name, $text)) { throw new WbHttpError(500, '백업 파일을 저장할 수 없습니다. api/data 폴더 권한을 확인해 주세요.'); } $keep = wb_int(wb_prop(wb_system_settings(), 'backupKeep', 14), 14); $list = glob($dir . '/backup-*.php'); sort($list); while (count($list) > max(1, $keep)) { @unlink(array_shift($list)); } return array('name' => $name, 'bytes' => strlen($text)); }
/* 하루 1회 정리(그날 첫 로그인 때 · 운영 서버에는 예약 작업이 없으므로) : 보관기간 지난 예약 파기 · 오래된 통계 원본 · 만료 세션 · 자동 백업 */
function wb_daily_tasks($c) { try { $set = wb_system_settings(); $today = wb_today(); if (wb_prop($set, 'lastDaily') === $today) { return; } if (wb_get('SELECT `key` FROM system_settings WHERE `key` = ?', array('lastDaily'))) { wb_update('system_settings', array('value' => wb_enc($today), 'updated_at' => wb_now()), '`key` = ?', array('lastDaily')); } else { wb_insert('system_settings', array('key' => 'lastDaily', 'value' => wb_enc($today), 'updated_at' => wb_now())); } $n = 0;   /* 개인정보 자동 파기 안 함 (방문예약은 계속 보관 · 삭제는 관리자가 직접) */ $keep = wb_int(wb_prop($set, 'analyticsKeepDays', 400), 400); if ($keep > 0) { wb_del('analytics_events', 'created_at < ?', array(wb_now(wb_days(-$keep)))); } wb_del('user_sessions', 'expires_at < ?', array(wb_now())); wb_del('preview_tokens', 'expires_at < ?', array(wb_now())); wb_del('rate_limits', 'window_start < ?', array((string)(time() - 3600))); if (wb_prop($set, 'autoBackup', true) !== false) { wb_make_backup($c, 'auto'); } if ($n) { wb_log($c, null, 'submission.purge', 'submission', null, '보관기간 경과 ' . $n . '건 자동 파기'); } } catch (Exception $e) { wb_log_error('daily: ' . $e->getMessage()); } }
wb_route('GET', '/system/status', function ($c) { wb_must_super($c['user']); return array('status' => wb_system_status($c), 'settings' => wb_system_settings()); });
wb_route('PUT', '/system/settings', function ($c) { wb_must_super($c['user']); $b = $c['body']; if (wb_has($b, 'publicBaseUrl')) { $u = rtrim(trim(wb_str($b['publicBaseUrl'], 200)), '/'); if ($u !== '' && !preg_match('#^https?://[^\s/]+(/[^\s]*)?$#', $u)) { throw new WbHttpError(422, '서버 공개 주소는 http:// 또는 https:// 로 시작하는 주소여야 합니다.'); } $b['publicBaseUrl'] = $u; } foreach ($b as $k => $v) { if (!preg_match('/^[a-zA-Z]{1,40}$/', (string)$k)) { continue; } $val = wb_enc(is_array($v) ? wb_bo($c, $k, $v) : $v); if (wb_get('SELECT `key` FROM system_settings WHERE `key` = ?', array($k))) { wb_update('system_settings', array('value' => $val, 'updated_at' => wb_now()), '`key` = ?', array($k)); } else { wb_insert('system_settings', array('key' => $k, 'value' => $val, 'updated_at' => wb_now())); } } wb_log($c, null, 'system.settings', 'system', null, '시스템 설정 변경'); return array('settings' => wb_system_settings()); });
wb_route('GET', '/system/sms', function ($c) { wb_must_super($c['user']); return wb_sms_status($c); });
wb_route('PUT', '/system/sms', function ($c) {   /* 문자 업체 설정 저장 (최고관리자) — 비밀키 · API Key 는 비워 두면 기존 값 유지, 화면에 다시 표시하지 않음 */
  wb_must_super($c['user']);
  throw new WbHttpError(403, '문자 업체 설정(API Key · API Secret · 발신번호)은 서버의 api/config.php 에서만 변경합니다. 관리자 화면에서는 저장하지 않습니다.');   /* 운영 : 키는 서버 설정 파일에만 (화면 저장 경로 닫음) */
  $b = $c['body']; $old = wb_sms_cfg($c);
  $p = strtolower(trim(wb_str(isset($b['provider']) ? $b['provider'] : ''))); if (!in_array($p, array('', 'solapi', 'aligo', 'ncp', 'log'), true)) { throw new WbHttpError(422, '지원하지 않는 문자 업체입니다.'); }
  $v = function ($k) use ($b) { return isset($b[$k]) ? trim(wb_str($b[$k], 300)) : ''; };
  $key = $v('api_key') !== '' ? $v('api_key') : ($p === $old['provider'] || $p === '' ? $old['api_key'] : ''); $sec = $v('api_secret') !== '' ? $v('api_secret') : ($p === $old['provider'] || $p === '' ? $old['api_secret'] : '');
  if (!empty($b['clear_keys'])) { $key = ''; $sec = ''; }
  $sender = wb_sms_digits($v('sender')); if ($sender !== '' && !preg_match('/^(0\d{8,10}|1[5-9]\d{6})$/', $sender)) { throw new WbHttpError(422, '발신번호 형식이 올바르지 않습니다. (문자 업체에 등록 · 인증된 번호 · 예 02-1234-5678)'); }
  $data = array('provider' => $p, 'api_key' => $key, 'api_secret' => $sec, 'sender' => $sender, 'user_id' => $v('user_id'), 'service_id' => $v('service_id'));
  $why = $p === '' ? '' : wb_sms_ready(array_merge($old, $data, array('enabled' => true)));
  if ($why !== '') { throw new WbHttpError(422, '입력이 부족합니다 : ' . $why); }
  wb_sms_save_file($data);
  wb_log($c, null, 'system.sms_settings', 'system', null, '문자 설정 저장 · ' . ($p === '' ? '사용 안 함' : $p) . ($sender !== '' ? ' · 발신 ' . wb_sms_pretty($sender) : ''));
  return wb_sms_status(array_merge($c, array('config' => $c['config'])));
});
wb_route('POST', '/system/sms/test', function ($c) { wb_must_super($c['user']); if (!wb_rate('smstest:' . (int)$c['user']['id'], 3, 60)) { throw new WbHttpError(429, '잠시 후 다시 시도해 주세요.'); } $me = wb_get('SELECT phone FROM users WHERE id = ?', array((int)$c['user']['id'])); $to = wb_sms_mobile($me ? $me['phone'] : ''); if ($to === '') { throw new WbHttpError(422, '내 계정에 휴대전화번호를 먼저 입력해 주세요. (테스트 문자는 로그인한 최고관리자 본인 번호로만 보냅니다)'); } $cfg = wb_sms_cfg($c); $text = '[통합웹빌더] 문자 알림 테스트입니다.'; $r = wb_sms_send_logged($cfg, $to, $text, wb_sms_type($text), '문자 알림 테스트', 'test', 0);
  wb_log($c, null, 'system.sms_test', 'system', null, '문자 테스트 ' . wb_sms_mask($to) . ' · ' . ($r['ok'] ? '성공' : '실패 ' . $r['code'] . ($r['kind'] ? ' (' . $r['kind'] . ')' : '')));
  $ip = $r['ip'] !== '' ? $r['ip'] : ''; if (!$r['ok'] && $r['kind'] === 'ip' && $ip === '') { $x = wb_sms_server_ip(false); $ip = $x['ip']; }
  return array('ok' => (bool)$r['ok'], 'to' => wb_sms_mask($to), 'kind' => $r['kind'], 'label' => $r['label'], 'reason' => $r['reason'], 'code' => $r['ok'] ? '' : (string)$r['code'], 'raw' => $r['raw'], 'error' => $r['ok'] ? '' : $r['reason'], 'serverIp' => $ip, 'cidr' => $ip !== '' ? $ip . '/32' : ''); });
wb_route('GET', '/system/sms/ip', function ($c) {   /* 현재 서버 발신 IP (문자 업체가 인식하는 공인 IP · 6시간 보관, refresh=1 이면 새로 확인) */
  wb_must_super($c['user']); $x = wb_sms_server_ip(!empty($c['query']['refresh']));
  return array('ip' => (string)$x['ip'], 'cidr' => $x['ip'] !== '' ? $x['ip'] . '/32' : '', 'at' => (string)$x['at'], 'source' => (string)$x['src']); });
wb_route('POST', '/system/backup', function ($c) { wb_must_super($c['user']); $r = wb_make_backup($c, wb_str(wb_b($c, 'label'), 30)); wb_log($c, null, 'system.backup', 'system', null, '백업 생성 ' . $r['name'] . ' (' . wb_fmt_bytes($r['bytes']) . ')'); return $r; });
wb_route('GET', '/system/backups', function ($c) { wb_must_super($c['user']); $dir = WB_DATA_DIR . '/backups'; $list = array(); if (is_dir($dir)) { $files = glob($dir . '/backup-*.php'); rsort($files); foreach ($files as $f) { $list[] = array('name' => basename($f), 'bytes' => filesize($f), 'created_at' => wb_now(filemtime($f))); } } return array('backups' => $list, 'note' => '백업 파일은 api/data/backups/ 에 저장됩니다. FileZilla 로 내려받아 따로 보관하세요.'); });
wb_route('GET', '/system/backups/:name', function ($c, $p) { wb_must_super($c['user']); $f = wb_safe_join(WB_DATA_DIR . '/backups', basename((string)$p['name'])); if (!$f || !is_file($f) || !preg_match('/^backup-[a-z0-9\-]+\.php$/', basename($f))) { throw new WbHttpError(404, '백업 파일을 찾을 수 없습니다.'); } wb_log($c, null, 'system.backup_download', 'system', null, '백업 다운로드 ' . basename($f)); $raw = file_get_contents($f); $pos = strpos($raw, "\n"); wb_send_file(200, 'application/json; charset=utf-8', $pos === false ? '' : substr($raw, $pos + 1), preg_replace('/\.php$/', '.json', basename($f))); return null; });
wb_route('DELETE', '/system/backups/:name', function ($c, $p) { wb_must_super($c['user']); $f = wb_safe_join(WB_DATA_DIR . '/backups', basename((string)$p['name'])); if ($f && is_file($f) && preg_match('/^backup-[a-z0-9\-]+\.php$/', basename($f))) { @unlink($f); } return array(); });
wb_route('POST', '/system/restore', function ($c) {
  wb_must_super($c['user']); $raw = ''; if (count($c['files'])) { $raw = (string)@file_get_contents($c['files'][0]['tmp']); } elseif (wb_b($c, 'name')) { $f = wb_safe_join(WB_DATA_DIR . '/backups', basename(wb_str(wb_b($c, 'name')))); if ($f && is_file($f)) { $raw = (string)file_get_contents($f); } }
  if ($raw === '') { throw new WbHttpError(422, '복구할 백업 파일을 선택해 주세요.'); } if (strpos($raw, '<?php') === 0) { $pos = strpos($raw, "\n"); $raw = $pos === false ? '' : substr($raw, $pos + 1); }
  $d = json_decode($raw, true); if (!is_array($d) || empty($d['tables']) || !is_array($d['tables'])) { throw new WbHttpError(422, '백업 파일 형식이 올바르지 않습니다. (이 프로그램의 [백업 생성]으로 만든 파일만 복구할 수 있습니다)'); }
  wb_make_backup($c, 'before-restore'); $schema = wb_schema(); $me = (int)$c['user']['id']; $n = 0;
  wb_tx(function () use ($d, $schema, &$n) { foreach (wb_backup_tables() as $t) { if (!isset($d['tables'][$t]) || !is_array($d['tables'][$t]) || !isset($schema[$t])) { continue; } $cols = array(); foreach ($schema[$t] as $col) { if ($col[0][0] !== '_') { $cols[$col[0]] = true; } } wb_run('DELETE FROM `' . $t . '`'); foreach ($d['tables'][$t] as $row) { $ins = array(); foreach ((array)$row as $k => $v) { if (isset($cols[$k])) { $ins[$k] = $v; } } if (count($ins)) { wb_insert($t, $ins); $n++; } } } });
  wb_del('user_sessions', '1 = 1'); $u = wb_get('SELECT * FROM users WHERE id = ?', array($me)); if ($u) { $c['user'] = $u; }
  wb_log($c, null, 'system.restore', 'system', null, '백업 복구 (' . $n . ' 행)'); return array('restored' => $n, 'note' => '복구가 완료되었습니다. 모든 사용자는 다시 로그인해야 합니다.');
});
wb_route('GET', '/system/errors', function ($c) { wb_must_super($c['user']); $dir = WB_DATA_DIR . '/logs'; $out = array(); if (is_dir($dir)) { $files = glob($dir . '/error-*'); rsort($files); foreach (array_slice($files, 0, 7) as $f) { $lines = file($f, FILE_IGNORE_NEW_LINES); $lines = array_values(array_filter($lines, function ($l) { return strpos($l, '<?php') !== 0; })); $out[] = array('file' => basename($f), 'tail' => implode("\n", array_slice($lines, -60))); } } return array('files' => $out); });

/* ================= 공개 API (인증 없음) : 홈페이지 방문자용 ================= */
wb_route('GET', '/public/health', function ($c) { return array('app' => '통합웹빌더', 'version' => WB_VERSION, 'time' => wb_now(), 'platform' => 'php', 'db' => wb_db_driver()); }, array('open' => true));
wb_route('GET', '/public/:key/preview', function ($c, $p) { $s = wb_public_site($c, $p['key']); $token = wb_q($c, 'token'); $row = $token !== '' ? wb_get('SELECT id, data_json FROM preview_tokens WHERE site_id = ? AND token_hash = ? AND expires_at > ?', array((int)$s['id'], wb_sha256($token), wb_now())) : null; if (!$row || empty($row['data_json'])) { throw new WbHttpError(403, '미리보기 링크가 만료되었거나 올바르지 않습니다. 관리자에서 다시 [미리보기]를 눌러 주세요.'); } $d = wb_json_safe($row['data_json'], null); if (!is_object($d)) { throw new WbHttpError(403, '미리보기 데이터가 올바르지 않습니다.'); } return array('__raw' => $d); }, array('open' => true));
wb_route('GET', '/public/:key/published.json', function ($c, $p) { $s = wb_public_site($c, $p['key']); $snap = $s['published_snapshot_id'] ? wb_get('SELECT content_json FROM publish_snapshots WHERE id = ?', array((int)$s['published_snapshot_id'])) : null; if (!$snap) { throw new WbHttpError(404, '아직 게시된 내용이 없습니다.'); } wb_send_file(200, 'application/json; charset=utf-8', $snap['content_json'], '', array('Cache-Control' => 'public, max-age=60', 'Access-Control-Allow-Origin' => '*')); return null; }, array('open' => true));
wb_route('POST', '/public/:key/forms/:form', function ($c, $p) { return wb_submit_handler($c, wb_public_site($c, $p['key']), (string)$p['form']); }, array('open' => true));
wb_route('POST', '/reservations/create', function ($c) { $b = $c['body']; $s = null; if (!empty($b['site_key'])) { $s = wb_get("SELECT * FROM sites WHERE `key` = ? AND status = 'active'", array((string)$b['site_key'])); } elseif (!empty($b['site_id'])) { $s = wb_get("SELECT * FROM sites WHERE id = ? AND status = 'active'", array(wb_int($b['site_id']))); } if (!$s) { throw new WbHttpError(422, '사이트 정보(site_key 또는 site_id)가 필요합니다.'); } return wb_submit_handler($c, wb_public_site($c, $s['key']), !empty($b['form_key']) ? wb_str($b['form_key'], 40) : 'reserve'); }, array('open' => true));
wb_route('POST', '/public/:key/events', function ($c, $p) { $s = wb_public_site($c, $p['key']); $cfg = wb_get_setting((int)$s['id'], 'analytics'); if (isset($cfg->enabled) && $cfg->enabled === false) { return array('skipped' => true); } $b = $c['body']; $events = isset($b['events']) && is_array($b['events']) ? $b['events'] : array($b); $sid = preg_replace('/[^a-zA-Z0-9]/', '', wb_str(isset($b['sid']) ? $b['sid'] : '')); $sessionHash = wb_sha256(($sid !== '' ? $sid : ($c['ipHash'] . $c['ua'])) . '|' . wb_today()); $n = 0; foreach (array_slice($events, 0, 20) as $ev) { if (!is_array($ev)) { continue; } $event = isset($ev['event']) && in_array($ev['event'], array('pageview', 'click', 'submit'), true) ? $ev['event'] : 'pageview'; $utm = array(); foreach (array('utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content') as $k) { if (isset($ev['utm']) && is_array($ev['utm']) && !empty($ev['utm'][$k])) { $utm[$k] = wb_str($ev['utm'][$k], 100); } } wb_insert('analytics_events', array('site_id' => (int)$s['id'], 'session_hash' => $sessionHash, 'event' => $event, 'path' => wb_str(!empty($ev['path']) ? $ev['path'] : '/', 190), 'title' => wb_str(isset($ev['title']) ? $ev['title'] : '', 190), 'label' => wb_str(isset($ev['label']) ? $ev['label'] : '', 120), 'referrer_host' => wb_str(wb_host_of(isset($ev['referrer']) ? (string)$ev['referrer'] : ''), 120), 'device' => isset($ev['device']) && in_array($ev['device'], array('pc', 'tablet', 'mobile'), true) ? $ev['device'] : 'pc', 'screen_w' => !empty($ev['screen_w']) ? wb_int($ev['screen_w']) : null, 'screen_h' => !empty($ev['screen_h']) ? wb_int($ev['screen_h']) : null, 'utm_json' => count($utm) ? wb_enc($utm) : null, 'created_at' => wb_now())); $n++; } return array('count' => $n); }, array('open' => true));
wb_route('POST', '/public/:key/popups/:id/hit', function ($c, $p) { $s = wb_public_site($c, $p['key']); $col = wb_b($c, 'type') === 'click' ? 'clicks' : 'impressions'; wb_run('UPDATE popups SET ' . $col . ' = ' . $col . ' + 1 WHERE id = ? AND site_id = ?', array((int)$p['id'], (int)$s['id'])); return array(); }, array('open' => true));
wb_route('GET', '/public/:key/sitemap.xml', function ($c, $p) { $s = wb_public_site($c, $p['key']); $f = dirname(wb_published_html_path($c, $s)) . '/sitemap.xml'; if (is_file($f)) { wb_send_file(200, 'application/xml; charset=utf-8', file_get_contents($f), '', array('Cache-Control' => 'public, max-age=3600')); return null; } $base = wb_site_url($s); wb_send_file(200, 'application/xml; charset=utf-8', '<?xml version="1.0" encoding="UTF-8"?>' . "\n" . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n" . '<url><loc>' . wb_esc($base . '/index.html') . '</loc></url>' . "\n" . '</urlset>', '', array('Cache-Control' => 'public, max-age=3600')); return null; }, array('open' => true));
wb_route('GET', '/public/:key/robots.txt', function ($c, $p) { $s = wb_public_site($c, $p['key']); $f = dirname(wb_published_html_path($c, $s)) . '/robots.txt'; wb_send_file(200, 'text/plain; charset=utf-8', is_file($f) ? file_get_contents($f) : "User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /admin/\nSitemap: " . wb_site_url($s) . "/sitemap.xml\n"); return null; }, array('open' => true));
