<?php
/* 통합웹빌더 운영 API — 미디어(이미지 · 영상) 업로드 · 저장 : 공개 폴더 assets/uploads/{사이트}/{연월}/ (같은 서버의 홈페이지가 바로 씀) */
if (!defined('WB_API')) { http_response_code(404); exit; }
function wb_allowed_types() { return array('jpg' => 'image/jpeg', 'png' => 'image/png', 'gif' => 'image/gif', 'webp' => 'image/webp', 'mp4' => 'video/mp4', 'webm' => 'video/webm'); }   /* SVG 는 스크립트를 담을 수 있어 업로드 금지 (관리자와 같은 주소에서 열리므로) */
function wb_uploads_dir() { return WB_WEB_ROOT . '/assets/uploads'; }
function wb_media_out($m, $base) { $v = wb_arr($m['variants_json']); $url = $base . '/uploads/' . (!empty($v['src']) ? $v['src'] : $m['filename']); return array('id' => (int)$m['id'], 'name' => $m['original_name'], 'alt' => (string)$m['alt'], 'mime' => $m['mime'], 'size' => (int)$m['size'], 'width' => $m['width'] === null ? null : (int)$m['width'], 'height' => $m['height'] === null ? null : (int)$m['height'], 'url' => $url, 'thumb' => !empty($v['thumb']) ? $base . '/uploads/' . $v['thumb'] : $url, 'mobile' => !empty($v['mobile']) ? $base . '/uploads/' . $v['mobile'] : $url, 'pc' => $url, 'original' => !empty($v['original']) ? $base . '/uploads/' . $v['original'] : $url, 'folder_id' => $m['folder_id'] ? (int)$m['folder_id'] : null, 'usage' => 0, 'created_at' => $m['created_at'], 'is_image' => strpos($m['mime'], 'image/') === 0, 'kind' => $m['kind'] ? $m['kind'] : (strpos($m['mime'], 'video/') === 0 ? 'video' : 'image'), 'variants' => (object)$v, 'duration' => $m['duration'] === null ? null : (float)$m['duration']); }
function wb_media_of($c, $id, $ability = 'view') { $m = wb_get('SELECT * FROM media WHERE id = ? AND deleted_at IS NULL', array((int)$id)); if (!$m) { throw new WbHttpError(404, '파일을 찾을 수 없습니다.'); } wb_site_of($c, (int)$m['site_id'], $ability); return $m; }
function wb_file_by_field($c, $field) { foreach ($c['files'] as $f) { if ($f['field'] === $field) { return $f; } } return null; }
function wb_store_upload($c, $s, $file, $opts = array()) {
  $data = @file_get_contents($file['tmp']); if ($data === false) { throw new WbHttpError(422, $file['name'] . ' : 업로드 파일을 읽을 수 없습니다.'); }
  $sn = wb_sniff($data); $allowed = wb_allowed_types(); if (!$sn || !isset($allowed[$sn['ext']])) { throw new WbHttpError(422, $file['name'] . ' : 허용되지 않는 파일 형식입니다. (JPG · PNG · WebP · GIF · MP4)'); }
  if ($sn['ext'] === 'svg' && preg_match('/<script|on[a-z]+\s*=|javascript:/i', $data)) { throw new WbHttpError(422, $file['name'] . ' : 스크립트가 포함된 SVG 는 업로드할 수 없습니다.'); }
  $maxMb = !empty($c['config']['max_upload_mb']) ? (int)$c['config']['max_upload_mb'] : 50; if (strlen($data) > $maxMb * 1048576) { throw new WbHttpError(413, $file['name'] . ' : 파일이 너무 큽니다. (최대 ' . $maxMb . 'MB)'); }
  $hash = wb_sha256($data); $dup = wb_get('SELECT * FROM media WHERE site_id = ? AND hash = ? AND deleted_at IS NULL', array((int)$s['id'], $hash));
  if ($dup && empty($opts['forceNew'])) { $o = wb_media_out($dup, wb_media_base($c)); $o['duplicate'] = true; return $o; }
  $ym = date('Ym'); $dir = wb_uploads_dir() . '/' . $s['key'] . '/' . $ym; if (!is_dir($dir) && !@mkdir($dir, 0755, true)) { throw new WbHttpError(500, '업로드 폴더(assets/uploads)를 만들 수 없습니다. 폴더 권한(707)을 확인해 주세요.'); }
  $baseName = preg_replace('/[^a-z0-9\x{AC00}-\x{D7A3}\-_]/u', '', wb_slugify(preg_replace('/\.[^.]*$/', '', $file['name']))); if ($baseName === '') { $baseName = 'file'; } $baseName = wb_substr($baseName, 60); $stem = substr($hash, 0, 8) . '-' . $baseName;
  $rel = $s['key'] . '/' . $ym . '/' . $stem . '.' . $sn['ext']; if (@file_put_contents(wb_uploads_dir() . '/' . $rel, $data, LOCK_EX) === false) { throw new WbHttpError(500, '파일을 저장할 수 없습니다. assets/uploads 폴더 권한(707)을 확인해 주세요.'); }
  $variants = array('src' => $rel); $size = strpos($sn['mime'], 'image/') === 0 && $sn['ext'] !== 'svg' ? wb_image_size(wb_uploads_dir() . '/' . $rel, $sn['ext']) : array(null, null);
  foreach (array('m' => 'mobile', 't' => 'thumb') as $k => $name) { $vf = isset($opts['variants'][$k]) ? $opts['variants'][$k] : null; if (!$vf) { continue; } $vd = @file_get_contents($vf['tmp']); $vs = $vd === false ? null : wb_sniff($vd); if (!$vs || strpos($vs['mime'], 'image/') !== 0) { continue; } $vrel = $s['key'] . '/' . $ym . '/' . $stem . '-' . $k . '.' . $vs['ext']; if (@file_put_contents(wb_uploads_dir() . '/' . $vrel, $vd, LOCK_EX) !== false) { $variants[$name] = $vrel; } }
  if (!empty($opts['original'])) { $od = @file_get_contents($opts['original']['tmp']); $os = $od === false ? null : wb_sniff($od); if ($os) { $orel = $s['key'] . '/' . $ym . '/' . $stem . '-orig.' . $os['ext']; if (@file_put_contents(wb_uploads_dir() . '/' . $orel, $od, LOCK_EX) !== false) { $variants['original'] = $orel; } } }
  $id = wb_insert('media', array('site_id' => (int)$s['id'], 'folder_id' => !empty($opts['folderId']) ? (int)$opts['folderId'] : null, 'filename' => $rel, 'original_name' => wb_str($file['name'], 190), 'mime' => $sn['mime'], 'size' => strlen($data), 'width' => $size[0], 'height' => $size[1], 'alt' => wb_str(!empty($opts['alt']) ? $opts['alt'] : preg_replace('/\.[^.]*$/', '', $file['name']), 190), 'hash' => $hash, 'variants_json' => wb_enc($variants), 'keep_original' => !empty($opts['original']) ? 1 : 0, 'uploaded_by' => (int)$c['user']['id'], 'created_at' => wb_now(), 'kind' => strpos($sn['mime'], 'video/') === 0 ? 'video' : 'image', 'duration' => !empty($opts['duration']) ? (float)$opts['duration'] : null));
  return wb_media_out(wb_get('SELECT * FROM media WHERE id = ?', array($id)), wb_media_base($c));
}
function wb_upload_handler($c, $s) {
  wb_must($c['user'], (int)$s['id'], 'media'); if (!count($c['files'])) { throw new WbHttpError(422, '파일이 없습니다.'); }
  $mains = array(); foreach ($c['files'] as $f) { if ($f['field'] === 'files' || $f['field'] === 'file') { $mains[] = $f; } }
  $media = array(); $errors = array(); $i = 0;
  foreach ($mains as $f) { try { $media[] = wb_store_upload($c, $s, $f, array('folderId' => wb_int(wb_b($c, 'folder_id')), 'alt' => wb_str(wb_b($c, 'alt')), 'variants' => array('m' => wb_file_by_field($c, 'mobile_' . $i), 't' => wb_file_by_field($c, 'thumb_' . $i)), 'original' => wb_file_by_field($c, 'original_' . $i), 'duration' => (float)wb_b($c, 'duration_' . $i, 0))); } catch (WbHttpError $e) { $errors[] = $e->getMessage(); } $i++; }
  if (count($media)) { wb_log($c, (int)$s['id'], 'media.upload', 'media', null, '파일 업로드 ' . count($media) . '개'); }
  return array('media' => $media, 'errors' => $errors);
}
function wb_media_needles($m) { $v = wb_arr($m['variants_json']); $out = array(); foreach (array_merge(array($m['filename']), array_values($v)) as $x) { $b = basename((string)$x); if ($b !== '' && strlen($b) > 5) { $out[] = $b; } } return $out; }
function wb_usage_haystack($siteId) {
  $parts = array(); $ids = array();
  foreach (wb_all('SELECT v.content_json FROM page_versions v JOIN pages p ON p.id = v.page_id WHERE p.site_id = ?', array((int)$siteId)) as $r) { $parts[] = $r['content_json']; }
  foreach (wb_all('SELECT data_json FROM settings WHERE site_id = ?', array((int)$siteId)) as $r) { $parts[] = $r['data_json']; }
  foreach (wb_all("SELECT pc_media_id, mobile_media_id, video_media_id, poster_media_id, pc_src, mobile_src FROM popups WHERE site_id = ? AND status <> 'deleted'", array((int)$siteId)) as $r) { foreach (array('pc_media_id', 'mobile_media_id', 'video_media_id', 'poster_media_id') as $k) { if (!empty($r[$k])) { $ids[(int)$r[$k]] = true; } } $parts[] = (string)$r['pc_src']; $parts[] = (string)$r['mobile_src']; }
  foreach (wb_all('SELECT og_json, favicon_media_id, share_image_media_id FROM seo WHERE site_id = ?', array((int)$siteId)) as $r) { foreach (array('favicon_media_id', 'share_image_media_id') as $k) { if (!empty($r[$k])) { $ids[(int)$r[$k]] = true; } } $parts[] = (string)$r['og_json']; }
  foreach (wb_all("SELECT fields_json FROM section_types WHERE site_id = ? AND scope = 'saved'", array((int)$siteId)) as $r) { $parts[] = $r['fields_json']; }
  foreach (wb_all('SELECT content_json FROM publish_snapshots WHERE site_id = ?', array((int)$siteId)) as $r) { $parts[] = $r['content_json']; }
  return array('text' => implode("\n", $parts), 'ids' => $ids);
}
function wb_media_list($c, $s) {
  $q = $c['query']; $where = array('site_id = ?', 'deleted_at IS NULL'); $params = array((int)$s['id']);
  if (!empty($q['q'])) { $where[] = '(original_name LIKE ? OR alt LIKE ? OR filename LIKE ?)'; $like = '%' . $q['q'] . '%'; array_push($params, $like, $like, $like); }
  if (!empty($q['type']) && $q['type'] === 'image') { $where[] = "mime LIKE 'image/%'"; } if (!empty($q['type']) && $q['type'] === 'video') { $where[] = "mime LIKE 'video/%'"; }
  if (!empty($q['folder']) && $q['folder'] !== 'all') { if ($q['folder'] === 'root') { $where[] = 'folder_id IS NULL'; } else { $where[] = 'folder_id = ?'; $params[] = wb_int($q['folder']); } }
  $orders = array('recent' => 'id DESC', 'old' => 'id ASC', 'name' => 'original_name ASC, id DESC', 'size' => 'size DESC, id DESC'); $order = isset($q['sort']) && isset($orders[$q['sort']]) ? $orders[$q['sort']] : 'id DESC';
  $page = max(1, wb_int(isset($q['page']) ? $q['page'] : 1, 1)); $per = min(200, max(5, wb_int(isset($q['per']) ? $q['per'] : 40, 40))); $w = implode(' AND ', $where); $base = wb_media_base($c);
  $meta = array('folders' => array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all('SELECT id, name FROM media_folders WHERE site_id = ? ORDER BY sort, name', array((int)$s['id']))), 'total_bytes' => wb_int(wb_val('SELECT COALESCE(SUM(size), 0) FROM media WHERE site_id = ? AND deleted_at IS NULL', array((int)$s['id']))), 'count_image' => wb_int(wb_val("SELECT COUNT(*) FROM media WHERE site_id = ? AND deleted_at IS NULL AND mime LIKE 'image/%'", array((int)$s['id']))), 'count_video' => wb_int(wb_val("SELECT COUNT(*) FROM media WHERE site_id = ? AND deleted_at IS NULL AND mime LIKE 'video/%'", array((int)$s['id']))));
  if (!empty($q['unused']) && wb_bool($q['unused'])) { $hay = wb_usage_haystack((int)$s['id']); $all = array(); foreach (wb_all('SELECT * FROM media WHERE ' . $w . ' ORDER BY ' . $order, $params) as $m) { $used = isset($hay['ids'][(int)$m['id']]); if (!$used) { foreach (wb_media_needles($m) as $n) { if (strpos($hay['text'], $n) !== false) { $used = true; break; } } } if (!$used) { $all[] = $m; } } $rows = array(); foreach (array_slice($all, ($page - 1) * $per, $per) as $m) { $rows[] = wb_media_out($m, $base); } return array_merge(array('rows' => $rows, 'total' => count($all), 'page' => $page, 'pages' => max(1, (int)ceil(count($all) / $per))), $meta); }
  $total = wb_int(wb_val('SELECT COUNT(*) FROM media WHERE ' . $w, $params)); $rows = array(); foreach (wb_all('SELECT * FROM media WHERE ' . $w . ' ORDER BY ' . $order . ' LIMIT ' . $per . ' OFFSET ' . (($page - 1) * $per), $params) as $m) { $rows[] = wb_media_out($m, $base); }
  return array_merge(array('rows' => $rows, 'total' => $total, 'page' => $page, 'pages' => max(1, (int)ceil($total / $per))), $meta);
}
function wb_usages_of($c, $m) {
  $needles = wb_media_needles($m); $has = function ($s) use ($needles) { if ($s === null || $s === '') { return false; } foreach ($needles as $n) { if (strpos((string)$s, $n) !== false) { return true; } } return false; }; $out = array(); $push = function ($scope, $type, $title, $extra = array()) use (&$out) { $out[] = array_merge(array('scope' => $scope, 'type' => $type, 'title' => $title), $extra); };
  $liveVersions = array();
  foreach (wb_all('SELECT id, title, draft_version_id, published_version_id FROM pages WHERE site_id = ? AND deleted_at IS NULL', array((int)$m['site_id'])) as $pg) { $hit = array(); foreach (array(array($pg['draft_version_id'], '편집 중인 초안'), array($pg['published_version_id'], '게시된 내용')) as $pair) { if (empty($pair[0])) { continue; } $liveVersions[(int)$pair[0]] = true; $ver = wb_get('SELECT content_json FROM page_versions WHERE id = ?', array((int)$pair[0])); if ($ver && $has($ver['content_json']) && !in_array($pair[1], $hit, true)) { $hit[] = $pair[1]; } } if (count($hit)) { $push('live', 'page', '페이지 · ' . $pg['title'] . ' (' . implode(' · ', $hit) . ')', array('id' => (int)$pg['id'])); } }
  $names = array('site' => '기본정보 · 연락처', 'header' => '헤더', 'footer' => '푸터 · 사업자정보', 'design' => '브랜드 · 디자인', 'quick' => '퀵메뉴', 'seo' => '기본 SEO');
  foreach (wb_all('SELECT group_key, data_json FROM settings WHERE site_id = ?', array((int)$m['site_id'])) as $s) { if ($has($s['data_json'])) { $push('live', 'settings', '사이트 설정 · ' . (isset($names[$s['group_key']]) ? $names[$s['group_key']] : $s['group_key'])); } }
  foreach (wb_all("SELECT id, name, pc_media_id, mobile_media_id, video_media_id, poster_media_id, pc_src, mobile_src FROM popups WHERE site_id = ? AND status <> 'deleted'", array((int)$m['site_id'])) as $p) { if (in_array((int)$m['id'], array((int)$p['pc_media_id'], (int)$p['mobile_media_id'], (int)$p['video_media_id'], (int)$p['poster_media_id']), true) || $has($p['pc_src']) || $has($p['mobile_src'])) { $push('live', 'popup', '팝업 · ' . $p['name'], array('id' => (int)$p['id'])); } }
  foreach (wb_all('SELECT id, scope, og_json, favicon_media_id, share_image_media_id FROM seo WHERE site_id = ?', array((int)$m['site_id'])) as $s) { if (in_array((int)$m['id'], array((int)$s['favicon_media_id'], (int)$s['share_image_media_id']), true) || $has($s['og_json'])) { $push('live', 'seo', 'SEO · ' . ($s['scope'] === 'site' ? '사이트 기본(파비콘 · 대표 이미지)' : '페이지별')); } }
  foreach (wb_all("SELECT id, name, fields_json FROM section_types WHERE site_id = ? AND scope = 'saved'", array((int)$m['site_id'])) as $b) { if ($has($b['fields_json'])) { $push('live', 'block', '저장한 블록 · ' . $b['name'], array('id' => (int)$b['id'])); } }
  $snaps = wb_all('SELECT id, version_no, status, content_json FROM publish_snapshots WHERE site_id = ? ORDER BY version_no DESC', array((int)$m['site_id'])); $liveSnap = null; foreach ($snaps as $x) { if (empty($x['status']) || $x['status'] === 'published' || $x['status'] === 'local-only') { $liveSnap = $x; break; } }
  foreach ($snaps as $x) { if (!$has($x['content_json'])) { continue; } if ($liveSnap && (int)$x['id'] === (int)$liveSnap['id']) { $push('live', 'published', '게시된 사이트 (v' . $x['version_no'] . ' · 지금 공개 중)'); } else { $push('history', 'snapshot', '이전 게시본 v' . $x['version_no'] . ' (복원할 때 사용)'); } }
  if (count($needles)) { $like = array(); $args = array((int)$m['site_id']); foreach ($needles as $n) { $like[] = "v.content_json LIKE ? ESCAPE '!'"; $args[] = '%' . str_replace(array('!', '%', '_'), array('!!', '!%', '!_'), $n) . '%'; } $old = array(); foreach (wb_all('SELECT v.id, v.version_no, p.title FROM page_versions v JOIN pages p ON p.id = v.page_id WHERE p.site_id = ? AND (' . implode(' OR ', $like) . ') ORDER BY v.id DESC', $args) as $r) { if (!isset($liveVersions[(int)$r['id']])) { $old[] = $r; } } if (count($old)) { $names2 = array(); foreach (array_slice($old, 0, 3) as $r) { $names2[] = $r['title'] . ' v' . $r['version_no']; } $push('history', 'version', '이전 버전 ' . count($old) . '건 (' . implode(', ', $names2) . (count($old) > 3 ? ' …' : '') . ')'); } }
  return $out;
}
