<?php
/* 통합웹빌더 운영 API — 라우트 ① 설정 마법사 · 인증 · 알림 · 대시보드 · 광고주 · 사이트 · 설정 · 메뉴 · 게시 · 페이지 · 블록 · 폼 (Node lib/api.js 와 같은 응답 형식) */
if (!defined('WB_API')) { http_response_code(404); exit; }

function wb_site_stats($siteId) { $t = wb_today(); return array('today_visitors' => wb_int(wb_val("SELECT COUNT(DISTINCT session_hash) FROM analytics_events WHERE site_id = ? AND event = 'pageview' AND created_at >= ?", array((int)$siteId, $t . ' 00:00:00'))), 'pending' => wb_int(wb_val("SELECT COUNT(*) FROM form_submissions WHERE site_id = ? AND deleted_at IS NULL AND status IN ('new','checking')", array((int)$siteId))), 'new_subs' => wb_int(wb_val("SELECT COUNT(*) FROM form_submissions WHERE site_id = ? AND deleted_at IS NULL AND status = 'new'", array((int)$siteId))), 'media' => wb_int(wb_val('SELECT COUNT(*) FROM media WHERE site_id = ? AND deleted_at IS NULL', array((int)$siteId))), 'media_bytes' => wb_int(wb_val('SELECT COALESCE(SUM(size), 0) FROM media WHERE site_id = ? AND deleted_at IS NULL', array((int)$siteId))), 'pages' => wb_int(wb_val('SELECT COUNT(*) FROM pages WHERE site_id = ? AND deleted_at IS NULL', array((int)$siteId))), 'popups' => wb_int(wb_val("SELECT COUNT(*) FROM popups WHERE site_id = ? AND status = 'published'", array((int)$siteId)))); }
function wb_site_out($s, $c) {
  $adv = !empty($s['advertiser_id']) ? wb_get('SELECT id, name FROM advertisers WHERE id = ?', array((int)$s['advertiser_id'])) : null; $pub = wb_site_url($s);
  return array('id' => (int)$s['id'], 'key' => $s['key'], 'name' => $s['name'], 'advertiser_id' => !empty($s['advertiser_id']) ? (int)$s['advertiser_id'] : null, 'advertiser_name' => $adv ? $adv['name'] : '', 'field_name' => (string)$s['field_name'], 'domain' => (string)$s['domain'], 'public_url' => (string)$s['public_url'], 'preview_url' => (string)$s['preview_url'], 'editor_base' => $pub, 'sms_enabled' => function_exists('wb_site_sms_enabled') ? wb_site_sms_enabled((int)$s['id']) : true, 'managers' => array_map(function ($r) { return array('name' => $r['name'], 'role' => $r['role'], 'sms' => (int)$r['sms_notify'] === 1); }, wb_all("SELECT DISTINCT u.name, u.role, u.sms_notify FROM users u WHERE u.status = 'active' AND u.role <> 'super' AND (EXISTS (SELECT 1 FROM site_users su WHERE su.site_id = ? AND su.user_id = u.id) OR EXISTS (SELECT 1 FROM user_advertisers ua JOIN sites s2 ON s2.advertiser_id = ua.advertiser_id WHERE s2.id = ? AND ua.user_id = u.id)) ORDER BY u.name LIMIT 20", array((int)$s['id'], (int)$s['id']))), 'builtin_url' => '', 'tel' => (string)$s['tel'], 'contact_name' => (string)$s['contact_name'], 'status' => $s['status'], 'created_at' => $s['created_at'], 'updated_at' => $s['updated_at'], 'last_published_at' => $s['last_published_at'], 'notes' => (string)$s['notes'], 'template' => (string)$s['template'], 'single' => true, 'platform' => 'php',
    'deploy' => array('mode' => 'server', 'host' => '', 'port' => 21, 'user' => '', 'root' => '/', 'secure' => false, 'hasPass' => false, 'passiveHost' => '', 'pushConfig' => true, 'relay' => false, 'files' => true, 'hasRelayKey' => false, 'hosted' => $c ? wb_site_hosted_here($c, $s) : false),
    'role' => $c ? wb_site_role($c['user'], (int)$s['id']) : null, 'menu' => $c ? wb_menu_for($c['user'], (int)$s['id']) : null, 'stats' => wb_site_stats((int)$s['id']));
}
function wb_site_alerts($s) { $a = array(); if (empty($s['public_url'])) { $a[] = array('level' => 'warn', 'text' => '공개 홈페이지 주소가 없습니다.'); } if (empty($s['last_published_at'])) { $a[] = array('level' => 'info', 'text' => '아직 게시하지 않았습니다. 상단 [게시하기]를 눌러 공개 홈페이지에 반영하세요.'); } $seo = wb_get("SELECT description FROM seo WHERE site_id = ? AND scope = 'site'", array((int)$s['id'])); if (!$seo || empty($seo['description'])) { $a[] = array('level' => 'info', 'text' => 'SEO 설명이 비어 있습니다.'); } return $a; }
function wb_system_status($c) { $up = 0; foreach (wb_walk_files(WB_WEB_ROOT . '/assets/uploads') as $f) { $up += $f['size']; } $bk = is_dir(WB_DATA_DIR . '/backups') ? count(glob(WB_DATA_DIR . '/backups/backup-*.php')) : 0; $lf = WB_DATA_DIR . '/logs/error-' . wb_today() . '.log.php'; $drv = wb_db_driver(); $dbBytes = 0; if ($drv === 'sqlite') { foreach (array('', '-wal', '-shm') as $sfx) { $f = WB_DATA_DIR . '/webbuilder.sqlite' . $sfx; if (is_file($f)) { $dbBytes += (int)@filesize($f); } } } else { try { $dbBytes = wb_int(wb_val('SELECT COALESCE(SUM(data_length + index_length), 0) FROM information_schema.TABLES WHERE table_schema = DATABASE()')); } catch (Exception $e) { $dbBytes = 0; } }
  $bkFiles = is_dir(WB_DATA_DIR . '/backups') ? glob(WB_DATA_DIR . '/backups/backup-*.php') : array(); $lastBk = ''; foreach ((array)$bkFiles as $bf) { $t = @filemtime($bf); if ($t && $t > ($lastBk === '' ? 0 : strtotime($lastBk))) { $lastBk = date('Y-m-d H:i:s', $t); } }
  $lastPub = wb_get("SELECT version_no, created_at FROM publish_snapshots WHERE status IS NULL OR status IN ('published', 'local-only') ORDER BY id DESC LIMIT 1");
  return array('dataDir' => str_replace(str_replace('\\', '/', WB_WEB_ROOT) . '/', '', str_replace('\\', '/', WB_DATA_DIR)), 'db_bytes' => $dbBytes, 'db' => $drv, 'db_label' => $drv === 'sqlite' ? 'SQLite (파일 DB)' : 'MySQL / MariaDB', 'last_backup' => $lastBk, 'last_publish' => $lastPub ? array('version' => (int)$lastPub['version_no'], 'at' => $lastPub['created_at']) : null, 'uploads_bytes' => $up, 'backups' => $bk, 'node' => 'PHP ' . PHP_VERSION, 'php' => PHP_VERSION, 'uptime' => 0, 'baseUrl' => $c['baseUrl'], 'publicFromConfig' => true, 'platform' => 'php', 'errors_today' => is_file($lf) ? count(array_filter(file($lf), function ($l) { return strpos($l, '[') === 0; })) : 0); }
function wb_system_settings() { $o = array('backupKeep' => 14, 'autoBackup' => true, 'retentionDays' => 365, 'analyticsKeepDays' => 400); foreach (wb_all('SELECT `key`, `value` FROM system_settings') as $r) { $o[$r['key']] = wb_json_safe($r['value'], $r['value']); } return $o; }

/* ================= 설정 마법사 · 데이터 가져오기 ================= */
wb_route('GET', '/setup/status', function ($c) { return array('needsSetup' => !wb_int(wb_val('SELECT COUNT(*) FROM users')), 'hasSites' => (bool)wb_int(wb_val('SELECT COUNT(*) FROM sites')), 'templates' => wb_template_list(), 'version' => WB_VERSION, 'baseUrl' => $c['baseUrl'], 'platform' => 'php', 'importAvailable' => is_file(WB_DATA_DIR . '/import.php')); }, array('open' => true));
function wb_import_data($c, $uid) {
  $file = WB_DATA_DIR . '/import.php'; if (!is_file($file)) { return null; }
  $raw = file_get_contents($file); if (strpos($raw, '<?php') === 0) { $p = strpos($raw, "\n"); $raw = $p === false ? '' : substr($raw, $p + 1); }
  $d = json_decode($raw, true); if (!is_array($d) || empty($d['tables'])) { throw new WbHttpError(422, '가져올 데이터 파일(import.php)의 형식이 올바르지 않습니다.'); }
  $order = array('advertisers', 'sites', 'settings', 'menus', 'menu_items', 'section_types', 'pages', 'page_versions', 'forms', 'form_fields', 'media_folders', 'media', 'popups', 'seo', 'publish_snapshots', 'system_settings'); $report = array();
  $schema = wb_schema();
  wb_tx(function () use ($d, $order, $schema, $uid, &$report) {
    foreach ($order as $table) {
      if (empty($d['tables'][$table]) || !is_array($d['tables'][$table])) { continue; } $cols = array(); foreach ($schema[$table] as $col) { if ($col[0][0] !== '_') { $cols[$col[0]] = substr($col[1], 0, 1); } } $n = 0;
      foreach ($d['tables'][$table] as $row) { $ins = array(); foreach ($row as $k => $v) { if (isset($cols[$k])) { if ($v === '' && in_array($cols[$k], array('I', 'R', 'D'), true)) { $v = null; } $ins[$k] = $v; } } if ($table === 'sites') { $dj = wb_arr(isset($ins['deploy_json']) ? $ins['deploy_json'] : null); $dj['mode'] = 'server'; unset($dj['host'], $dj['user'], $dj['pass'], $dj['passiveHost']); $ins['deploy_json'] = wb_enc($dj); $ins['created_by'] = $uid; } if ($table === 'page_versions' || $table === 'pages' || $table === 'popups' || $table === 'forms' || $table === 'settings' || $table === 'media') { foreach (array('created_by', 'updated_by', 'uploaded_by') as $k) { if (isset($ins[$k])) { $ins[$k] = null; } } } wb_insert($table, $ins); $n++; }
      $report[$table] = $n;
    }
  });
  @rename($file, WB_DATA_DIR . '/import.done-' . date('Ymd-His') . '.php');
  return $report;
}
/* 처음 설정의 현장 정보(현장명 · 대표번호 · 이메일 · 주소 · 상담시간 · 공개 주소)를 사이트 설정에도 넣음 → 홈페이지 · 문자에 바로 사용 */
function wb_setup_site_info($siteId, $in, $uid) { try { $g = wb_get_setting($siteId, 'site'); if (!is_object($g)) { $g = new stdClass(); } if (!isset($g->site) || !is_object($g->site)) { $g->site = new stdClass(); } $map = array('name' => 'name', 'tel' => 'tel', 'email' => 'email', 'address' => 'address', 'consultHours' => 'consultHours', 'public_url' => 'url'); foreach ($map as $k => $to) { if (isset($in[$k]) && trim((string)$in[$k]) !== '') { $g->site->$to = wb_str($in[$k], 200); } } wb_put_setting($siteId, 'site', $g, $uid); } catch (Exception $e) { wb_log_error('setup site info: ' . $e->getMessage()); } }
wb_route('POST', '/setup', function ($c) {
  if (wb_int(wb_val('SELECT COUNT(*) FROM users'))) { throw new WbHttpError(403, '이미 설정이 완료되었습니다. 로그인해 주세요.'); }
  $b = $c['body']; $err = wb_valid_password(isset($b['password']) ? $b['password'] : ''); if ($err) { throw new WbHttpError(422, $err); }
  $loginId = wb_lower(trim(wb_str(isset($b['loginId']) ? $b['loginId'] : ''))); if (!preg_match('/^[a-z0-9_.@\-]{3,40}$/', $loginId)) { throw new WbHttpError(422, '로그인 아이디는 영문 · 숫자 3~40자로 입력해 주세요.'); }
  $email = wb_lower(trim(wb_str(isset($b['email']) ? $b['email'] : ''))); if ($email === '') { $email = strpos($loginId, '@') !== false ? $loginId : $loginId . '@local'; }
  $uid = wb_insert('users', array('login_id' => $loginId, 'email' => $email, 'password_hash' => wb_hash_password($b['password']), 'name' => wb_str(isset($b['name']) ? $b['name'] : '', 60) ?: '최고관리자', 'role' => 'super', 'status' => 'active', 'phone' => wb_str(isset($b['phone']) ? $b['phone'] : '', 30), 'company' => wb_str(isset($b['company']) ? $b['company'] : '', 80), 'tel' => wb_str(isset($b['tel']) ? $b['tel'] : '', 30), 'created_at' => wb_now(), 'updated_at' => wb_now()));
  $c['user'] = wb_get('SELECT * FROM users WHERE id = ?', array($uid));
  $imported = null; $site = null;
  if (is_file(WB_DATA_DIR . '/import.php') && !wb_int(wb_val('SELECT COUNT(*) FROM sites'))) { $imported = wb_import_data($c, $uid); $site = wb_get("SELECT * FROM sites WHERE status <> 'deleted' ORDER BY id LIMIT 1"); }
  elseif (!empty($b['site']) && is_array($b['site']) && !empty($b['site']['name'])) { $site = wb_create_site_from_input($c, $b['site'], $uid); wb_setup_site_info((int)$site['id'], $b['site'], $uid); }
  wb_log($c, $site ? (int)$site['id'] : null, 'setup', 'system', null, '초기 설정 완료 · 최고관리자 ' . $loginId . ($imported ? ' · 기존 데이터 가져오기 ' . wb_enc($imported) : ''));
  $token = wb_create_session($uid, $c);
  return array('token' => $token, 'user' => wb_public_user($c['user']), 'site' => $site ? wb_site_out($site, $c) : null, 'imported' => $imported);
}, array('open' => true));

/* ================= 인증 ================= */
wb_route('POST', '/auth/login', function ($c) { if (!wb_rate('login:' . $c['ipHash'], 20, 60)) { throw new WbHttpError(429, '로그인 시도가 너무 많습니다. 1분 뒤 다시 시도해 주세요.'); } $r = wb_login(wb_b($c, 'loginId'), wb_b($c, 'password'), $c); wb_daily_tasks($c); $u = wb_get('SELECT * FROM users WHERE id = ?', array((int)$r['user']['id'])); try { $c2 = $c; $c2['user'] = $u; wb_log($c2, null, 'auth.login', 'user', (int)$u['id'], '로그인 ' . $u['login_id']); } catch (Exception $e) {} $sites = array(); foreach (wb_sites($u) as $s) { $sites[] = wb_site_out($s, array('user' => $u, 'host' => $c['host'], 'config' => $c['config'], 'baseUrl' => $c['baseUrl'])); } return array_merge(array('sites' => $sites, 'platform' => 'php'), $r); }, array('open' => true));
wb_route('POST', '/auth/logout', function ($c) { if (!empty($c['user'])) { try { wb_log($c, null, 'auth.logout', 'user', (int)$c['user']['id'], '로그아웃 ' . $c['user']['login_id']); } catch (Exception $e) {} } wb_logout($c['token']); return array(); }, array('open' => true));
wb_route('GET', '/auth/me', function ($c) { $sites = array(); foreach (wb_sites($c['user']) as $s) { $sites[] = wb_site_out($s, $c); } $adv = array(); foreach (wb_advertisers($c['user']) as $a) { $adv[] = array('id' => (int)$a['id'], 'name' => $a['name']); } return array('user' => $c['user'], 'sites' => $sites, 'advertisers' => $adv, 'roles' => wb_roles(), 'siteRoles' => wb_site_roles(), 'statuses' => wb_statuses(), 'baseUrl' => $c['baseUrl'], 'version' => WB_VERSION, 'build' => WB_BUILD, 'deployed' => WB_DEPLOYED, 'platform' => 'php'); });
wb_route('PUT', '/auth/password', function ($c) { $u = wb_get('SELECT * FROM users WHERE id = ?', array((int)$c['user']['id'])); if (!wb_verify_password(wb_str(wb_b($c, 'current')), $u['password_hash'])) { throw new WbHttpError(422, '현재 비밀번호가 올바르지 않습니다.'); } $err = wb_valid_password(wb_b($c, 'next')); if ($err) { throw new WbHttpError(422, $err); } if ((string)wb_b($c, 'next') === (string)wb_b($c, 'current')) { throw new WbHttpError(422, '현재 비밀번호와 다른 새 비밀번호를 입력해 주세요.'); } wb_update('users', array('password_hash' => wb_hash_password(wb_b($c, 'next')), 'must_change_password' => 0, 'updated_at' => wb_now()), 'id = ?', array((int)$u['id'])); wb_log($c, null, 'user.password', 'user', (int)$u['id'], '비밀번호 변경'); return array(); });
wb_route('PUT', '/auth/profile', function ($c) { $d = array(); foreach (array('name', 'email', 'phone', 'company', 'tel') as $k) { if (wb_has($c['body'], $k)) { $d[$k] = wb_str($c['body'][$k], 120); } } $d['updated_at'] = wb_now(); wb_update('users', $d, 'id = ?', array((int)$c['user']['id'])); return array('user' => wb_public_user(wb_get('SELECT * FROM users WHERE id = ?', array((int)$c['user']['id'])))); });
wb_route('GET', '/notifications', function ($c) { $sites = array(); foreach (wb_sites($c['user']) as $s) { if (wb_can($c['user'], (int)$s['id'], 'submissions')) { $sites[] = (int)$s['id']; } } if (!count($sites)) { return array('unseen' => 0, 'items' => array()); } $gsFailed = function_exists('wb_gs_failed_count') ? wb_gs_failed_count($sites) : 0; if (function_exists('wb_gs_has_due') && wb_gs_has_due()) { $cc = $c; wb_after_response(function () use ($cc) { wb_gs_retry_due($cc, 2, 15); }); } $since = !empty($c['user']['notif_seen_at']) ? $c['user']['notif_seen_at'] : '2000-01-01'; $items = array_map(function ($r) { return wb_ints($r, array('id', 'site_id')); }, wb_all('SELECT s.id, s.name, s.site_id, s.created_at, st.name AS site_name FROM form_submissions s JOIN sites st ON st.id = s.site_id WHERE s.site_id IN (' . wb_in($sites) . ') AND s.deleted_at IS NULL AND s.created_at > ? ORDER BY s.id DESC LIMIT 10', array_merge($sites, array($since)))); return array('unseen' => wb_int(wb_val('SELECT COUNT(*) FROM form_submissions WHERE site_id IN (' . wb_in($sites) . ') AND deleted_at IS NULL AND created_at > ?', array_merge($sites, array($since)))), 'items' => $items, 'gs_failed' => $gsFailed); });
wb_route('POST', '/notifications/seen', function ($c) { wb_update('users', array('notif_seen_at' => wb_now()), 'id = ?', array((int)$c['user']['id'])); return array(); });

/* ================= 대시보드 ================= */
wb_route('GET', '/dashboard', function ($c) {
  $sites = wb_sites($c['user']); $t = wb_today(); $week = wb_today(wb_days(-6)); $list = array(); $ids = array(); $subIds = array();
  foreach ($sites as $s) { $o = wb_site_out($s, $c); $o['week_visitors'] = wb_int(wb_val("SELECT COUNT(DISTINCT session_hash) FROM analytics_events WHERE site_id = ? AND event = 'pageview' AND created_at >= ?", array((int)$s['id'], $week . ' 00:00:00'))); $o['month_subs'] = wb_int(wb_val('SELECT COUNT(*) FROM form_submissions WHERE site_id = ? AND deleted_at IS NULL AND created_at >= ?', array((int)$s['id'], substr($t, 0, 7) . '-01 00:00:00'))); $o['alerts'] = wb_site_alerts($s); $list[] = $o; $ids[] = (int)$s['id']; if (wb_can($c['user'], (int)$s['id'], 'submissions') || wb_can($c['user'], (int)$s['id'], 'submissions.view')) { $subIds[] = (int)$s['id']; } }
  $recent = array(); if (count($subIds)) { foreach (wb_all('SELECT s.id, s.site_id, st.name AS site_name, s.name, s.phone, s.visit_date, s.visit_time, s.status, s.created_at FROM form_submissions s JOIN sites st ON st.id = s.site_id WHERE s.site_id IN (' . wb_in($subIds) . ') AND s.deleted_at IS NULL ORDER BY s.id DESC LIMIT 10', $subIds) as $r) { $r = wb_ints($r, array('id', 'site_id')); $r['phone'] = wb_mask_phone($r['phone'], wb_can($c['user'], $r['site_id'], 'submissions')); $st = wb_statuses(); $r['status_label'] = isset($st[$r['status']]) ? $st[$r['status']] : $r['status']; $recent[] = $r; } }
  $logs = wb_is_super($c['user']) ? wb_all('SELECT l.*, u.name AS user_name, st.name AS site_name FROM activity_logs l LEFT JOIN users u ON u.id = l.user_id LEFT JOIN sites st ON st.id = l.site_id ORDER BY l.id DESC LIMIT 12') : (count($ids) ? wb_all('SELECT l.*, u.name AS user_name, st.name AS site_name FROM activity_logs l LEFT JOIN users u ON u.id = l.user_id LEFT JOIN sites st ON st.id = l.site_id WHERE l.site_id IN (' . wb_in($ids) . ') ORDER BY l.id DESC LIMIT 12', $ids) : array());
  $pending = 0; $tv = 0; foreach ($list as $o) { $pending += $o['stats']['pending']; $tv += $o['stats']['today_visitors']; }
  $todaySubs = count($subIds) ? wb_int(wb_val('SELECT COUNT(*) FROM form_submissions WHERE site_id IN (' . wb_in($subIds) . ') AND deleted_at IS NULL AND created_at >= ?', array_merge($subIds, array($t . ' 00:00:00')))) : 0;
  $newSubs = count($subIds) ? wb_int(wb_val("SELECT COUNT(*) FROM form_submissions WHERE site_id IN (" . wb_in($subIds) . ") AND deleted_at IS NULL AND status = 'new'", $subIds)) : 0;
  $smsFailed = count($subIds) ? wb_int(wb_val("SELECT COUNT(*) FROM sms_logs WHERE site_id IN (" . wb_in($subIds) . ") AND status = 'failed' AND created_at >= ?", array_merge($subIds, array(wb_now(time() - 7 * 86400))))) : 0;
  $lastPub = count($ids) ? wb_get("SELECT p.version_no, p.created_at, st.name AS site_name FROM publish_snapshots p JOIN sites st ON st.id = p.site_id WHERE p.site_id IN (" . wb_in($ids) . ") AND (p.status IS NULL OR p.status IN ('published', 'local-only')) ORDER BY p.id DESC LIMIT 1", $ids) : null;
  $smsState = null; if (wb_is_super($c['user']) && function_exists('wb_sms_status')) { try { $ss = wb_sms_status($c); $smsState = array('state' => $ss['state'], 'provider' => $ss['providerName'], 'serverIp' => $ss['serverIp']); } catch (Exception $e) { $smsState = null; } }
  $lastPubOut = $lastPub ? array('version' => (int)$lastPub['version_no'], 'at' => $lastPub['created_at'], 'site' => $lastPub['site_name']) : null;
  $lastRs = count($ids) ? wb_get("SELECT created_at, summary FROM activity_logs WHERE action = 'site.publish_restore' AND site_id IN (" . wb_in($ids) . ") ORDER BY id DESC LIMIT 1", $ids) : null;
  if ($lastRs && (!$lastPub || strcmp((string)$lastRs['created_at'], (string)$lastPub['created_at']) >= 0)) { if (!$lastPubOut) { $lastPubOut = array('version' => 0, 'at' => '', 'site' => ''); } $lastPubOut['restored'] = array('at' => $lastRs['created_at'], 'summary' => (string)$lastRs['summary']); }
  return array('extra' => array('today_subs' => $todaySubs, 'new_subs' => $newSubs, 'sms_failed' => $smsFailed, 'last_publish' => $lastPubOut, 'sms' => $smsState), 'sites' => $list, 'recent' => $recent, 'logs' => array_map(function ($r) { return wb_ints($r, array('id', 'site_id', 'user_id', 'target_id')); }, $logs), 'totals' => array('sites' => count($sites), 'pending' => $pending, 'today_visitors' => $tv, 'users' => wb_is_super($c['user']) ? wb_int(wb_val("SELECT COUNT(*) FROM users WHERE status = 'active'")) : null), 'system' => wb_is_super($c['user']) ? wb_system_status($c) : null);
});

/* ================= 광고주 · 사이트 ================= */
function wb_adv_out($a) { return array('id' => (int)$a['id'], 'name' => $a['name'], 'contact_name' => (string)$a['contact_name'], 'contact_tel' => (string)$a['contact_tel'], 'contact_email' => (string)$a['contact_email'], 'memo' => (string)$a['memo'], 'status' => $a['status'], 'created_at' => $a['created_at'], 'sites' => array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all("SELECT id, `key`, name FROM sites WHERE advertiser_id = ? AND status <> 'deleted' ORDER BY id", array((int)$a['id']))), 'users' => array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all('SELECT u.id, u.name, u.login_id, ua.role FROM user_advertisers ua JOIN users u ON u.id = ua.user_id WHERE ua.advertiser_id = ? ORDER BY u.name', array((int)$a['id'])))); }
function wb_adv_input($b) { $d = array(); if (wb_has($b, 'name')) { $d['name'] = trim(wb_str($b['name'], 120)); if ($d['name'] === '') { throw new WbHttpError(422, '광고주 이름을 입력해 주세요.'); } } foreach (array('contact_name', 'contact_tel', 'contact_email', 'memo') as $k) { if (wb_has($b, $k)) { $d[$k] = trim(wb_str($b[$k], $k === 'memo' ? 1000 : 120)); } } if (wb_has($b, 'status')) { $d['status'] = in_array($b['status'], array('active', 'paused'), true) ? $b['status'] : 'active'; } return $d; }
wb_route('GET', '/advertisers', function ($c) { return array('advertisers' => array_map('wb_adv_out', wb_advertisers($c['user']))); });
wb_route('POST', '/advertisers', function ($c) { wb_must_super($c['user']); $d = wb_adv_input($c['body']); if (empty($d['name'])) { throw new WbHttpError(422, '광고주 이름을 입력해 주세요.'); } $d['status'] = isset($d['status']) ? $d['status'] : 'active'; $d['created_at'] = wb_now(); $d['updated_at'] = wb_now(); $id = wb_insert('advertisers', $d); foreach ((array)wb_b($c, 'site_ids', array()) as $sid) { wb_update('sites', array('advertiser_id' => $id), 'id = ?', array(wb_int($sid))); } wb_log($c, null, 'advertiser.create', 'advertiser', $id, '광고주 등록 ' . $d['name']); return array('advertiser' => wb_adv_out(wb_get('SELECT * FROM advertisers WHERE id = ?', array($id)))); });
wb_route('PUT', '/advertisers/:id', function ($c, $p) { wb_must_super($c['user']); $a = wb_get("SELECT * FROM advertisers WHERE id = ? AND status <> 'deleted'", array((int)$p['id'])); if (!$a) { throw new WbHttpError(404, '광고주를 찾을 수 없습니다.'); } $d = wb_adv_input($c['body']); $d['updated_at'] = wb_now(); wb_update('advertisers', $d, 'id = ?', array((int)$a['id'])); if (is_array(wb_b($c, 'site_ids'))) { wb_run('UPDATE sites SET advertiser_id = NULL WHERE advertiser_id = ?', array((int)$a['id'])); foreach (wb_b($c, 'site_ids') as $sid) { wb_update('sites', array('advertiser_id' => (int)$a['id']), 'id = ?', array(wb_int($sid))); } } wb_log($c, null, 'advertiser.update', 'advertiser', (int)$a['id'], '광고주 수정 ' . (isset($d['name']) ? $d['name'] : $a['name'])); return array('advertiser' => wb_adv_out(wb_get('SELECT * FROM advertisers WHERE id = ?', array((int)$a['id'])))); });
wb_route('DELETE', '/advertisers/:id', function ($c, $p) { wb_must_super($c['user']); $a = wb_get('SELECT * FROM advertisers WHERE id = ?', array((int)$p['id'])); if (!$a) { throw new WbHttpError(404, '광고주를 찾을 수 없습니다.'); } wb_update('advertisers', array('status' => 'deleted', 'updated_at' => wb_now()), 'id = ?', array((int)$a['id'])); wb_del('user_advertisers', 'advertiser_id = ?', array((int)$a['id'])); wb_log($c, null, 'advertiser.delete', 'advertiser', (int)$a['id'], '광고주 삭제(보관) ' . $a['name']); return array(); });
wb_route('GET', '/sites', function ($c) { $out = array(); foreach (wb_sites($c['user']) as $s) { $out[] = wb_site_out($s, $c); } return array('sites' => $out, 'templates' => wb_is_super($c['user']) ? wb_template_list() : array()); });
wb_route('GET', '/sites/:id', function ($c, $p) { return array('site' => wb_site_out(wb_site_of($c, $p['id']), $c)); });
function wb_create_site_from_input($c, $b, $userId) {
  $key = wb_keyify(!empty($b['key']) ? $b['key'] : wb_slugify(isset($b['name']) ? $b['name'] : '')); if ($key === '' || strlen($key) < 2) { throw new WbHttpError(422, '사이트 식별값(영문 · 숫자)을 입력해 주세요.'); }
  if (wb_get('SELECT id FROM sites WHERE `key` = ?', array($key))) { throw new WbHttpError(422, '이미 사용 중인 식별값입니다: ' . $key); }
  $publicUrl = preg_replace('#/(index\.html)?$#', '', trim(wb_str(isset($b['public_url']) ? $b['public_url'] : '', 190))); $n = wb_now();
  $id = wb_insert('sites', array('key' => $key, 'name' => wb_str($b['name'], 80), 'field_name' => wb_str(isset($b['field_name']) ? $b['field_name'] : '', 80), 'domain' => wb_str(isset($b['domain']) ? $b['domain'] : '', 120) ?: wb_host_of($publicUrl), 'public_url' => $publicUrl, 'preview_url' => rtrim(trim(wb_str(isset($b['preview_url']) ? $b['preview_url'] : '', 190)), '/'), 'export_path' => '', 'status' => 'active', 'tel' => wb_str(isset($b['tel']) ? $b['tel'] : '', 30), 'contact_name' => wb_str(isset($b['contact_name']) ? $b['contact_name'] : '', 60), 'notes' => wb_str(isset($b['notes']) ? $b['notes'] : '', 1000), 'template' => wb_str(!empty($b['template']) ? $b['template'] : 'template', 40), 'deploy_json' => wb_enc(array('mode' => 'server')), 'created_by' => $userId ? (int)$userId : null, 'created_at' => $n, 'updated_at' => $n));
  $siteOpts = array('site' => array('name' => wb_str($b['name'], 80))); if (!empty($b['tel'])) { $siteOpts['site']['tel'] = wb_str($b['tel'], 30); } if ($publicUrl !== '') { $siteOpts['site']['url'] = $publicUrl; }
  if (!empty($b['template']) && strpos((string)$b['template'], 'copy:') === 0) { wb_copy_site(wb_int(substr($b['template'], 5)), $id, $userId); } else { wb_seed($id, wb_load_template(!empty($b['template']) ? $b['template'] : 'template'), $userId, $siteOpts);   /* 기본 : 신규 현장용 빈 템플릿 */ }
  return wb_get('SELECT * FROM sites WHERE id = ?', array($id));
}
wb_route('POST', '/sites', function ($c) { wb_must_super($c['user']); if (wb_int(wb_val("SELECT COUNT(*) FROM sites WHERE status <> 'deleted'"))) { throw new WbHttpError(422, '이 관리자는 현장 1개 전용입니다. 새 현장은 같은 배포본을 그 현장 서버에 따로 설치해 주세요.'); } $s = wb_create_site_from_input($c, $c['body'], (int)$c['user']['id']); wb_log($c, (int)$s['id'], 'site.create', 'site', (int)$s['id'], '사이트 등록 ' . $s['name'] . ' (' . $s['key'] . ')'); return array('site' => wb_site_out($s, $c)); });
wb_route('PUT', '/sites/:id', function ($c, $p) {
  $s = wb_site_of($c, $p['id'], 'manage'); $b = $c['body']; $d = array();
  foreach (array('name', 'field_name', 'domain', 'public_url', 'preview_url', 'tel', 'contact_name', 'notes') as $k) { if (wb_has($b, $k)) { $d[$k] = trim(wb_str($b[$k], $k === 'notes' ? 1000 : 120)); } }
  if (wb_has($b, 'advertiser_id')) { wb_must_super($c['user']); $aid = wb_int($b['advertiser_id']); if ($aid && !wb_get("SELECT id FROM advertisers WHERE id = ? AND status <> 'deleted'", array($aid))) { throw new WbHttpError(422, '광고주를 찾을 수 없습니다.'); } $d['advertiser_id'] = $aid ? $aid : null; }
  if (isset($d['public_url'])) { $d['public_url'] = preg_replace('#/(index\.html)?$#', '', $d['public_url']); } if (isset($d['preview_url'])) { $d['preview_url'] = rtrim($d['preview_url'], '/'); }
  if (!empty($b['status']) && in_array($b['status'], array('active', 'paused'), true)) { wb_must_super($c['user']); $d['status'] = $b['status']; }
  $d['updated_at'] = wb_now(); wb_update('sites', $d, 'id = ?', array((int)$s['id']));
  if (wb_has($b, 'sms_enabled')) { $n = wb_get_setting((int)$s['id'], 'notify'); $n->sms = wb_bool($b['sms_enabled']) || $b['sms_enabled'] === 1 || $b['sms_enabled'] === '1'; wb_put_setting((int)$s['id'], 'notify', $n, (int)$c['user']['id']); wb_log($c, (int)$s['id'], 'site.sms_toggle', 'site', (int)$s['id'], '방문예약 문자 알림 ' . ($n->sms ? '사용' : '사용 안 함')); }
  if (isset($d['tel'])) { $site = wb_get_setting((int)$s['id'], 'site'); if (!isset($site->site) || !is_object($site->site)) { $site->site = new stdClass(); } $site->site->tel = $d['tel']; wb_put_setting((int)$s['id'], 'site', $site, (int)$c['user']['id']); }
  if (isset($d['name'])) { $site = wb_get_setting((int)$s['id'], 'site'); if (!isset($site->site) || !is_object($site->site)) { $site->site = new stdClass(); } $site->site->name = $d['name']; wb_put_setting((int)$s['id'], 'site', $site, (int)$c['user']['id']); }
  wb_log($c, (int)$s['id'], 'site.update', 'site', (int)$s['id'], '사이트 정보 수정', null, array_keys($d));
  return array('site' => wb_site_out(wb_get('SELECT * FROM sites WHERE id = ?', array((int)$s['id'])), $c));
});
wb_route('DELETE', '/sites/:id', function ($c, $p) { wb_must_super($c['user']); $s = wb_site_of($c, $p['id']); wb_update('sites', array('status' => 'deleted', 'updated_at' => wb_now()), 'id = ?', array((int)$s['id'])); wb_log($c, (int)$s['id'], 'site.delete', 'site', (int)$s['id'], '사이트 삭제(보관) ' . $s['name']); return array(); });
wb_route('GET', '/sites/:id/connect', function ($c, $p) { $s = wb_site_of($c, $p['id']); $pub = wb_site_url($s); $cfg = array('enabled' => true, 'siteKey' => $s['key'], 'api' => './api/index.php?r=', 'published' => '', 'reserve' => './api/index.php?r=/public/' . rawurlencode($s['key']) . '/forms/reserve', 'timeout' => 2500, 'analytics' => true, 'single' => true); return array('cmsConfig' => 'window.CMS_CONFIG = ' . wb_enc($cfg) . ';', 'config' => $cfg, 'mode' => 'server', 'relay' => false, 'hasRelayKey' => false, 'publicUrl' => $pub, 'publishedUrl' => $pub . '/index.html', 'manifestUrl' => '', 'formEndpoint' => $c['baseUrl'] . '/api/index.php?r=/public/' . rawurlencode($s['key']) . '/forms/reserve', 'relayAdmin' => '', 'relayHealth' => '', 'uploadsUrl' => $c['baseUrl'] . '/assets/uploads/' . $s['key'] . '/', 'eventsEndpoint' => $c['baseUrl'] . '/api/index.php?r=/public/' . rawurlencode($s['key']) . '/events', 'published' => $s['last_published_at'], 'templateDir' => true, 'builtinUrl' => '', 'baseUrl' => $c['baseUrl'], 'serverPublic' => true, 'localOnly' => false, 'relayState' => null, 'hosted' => wb_site_hosted_here($c, $s), 'platform' => 'php'); });
wb_route('POST', '/sites/:id/deploy/check', function ($c, $p) { wb_must_super($c['user']); return wb_deploy_check($c, wb_site_of($c, $p['id'])); });
wb_route('GET', '/sites/:id/deploy/bundle-info', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'publish'); $last = wb_get('SELECT version_no, created_at FROM publish_snapshots WHERE site_id = ? AND status = ? ORDER BY version_no DESC LIMIT 1', array((int)$s['id'], 'published')); $up = count(wb_walk_files(WB_WEB_ROOT . '/assets/uploads/' . $s['key'])); return array('published' => (bool)$last, 'version' => $last ? (int)$last['version_no'] : 0, 'publishedAt' => $last ? $last['created_at'] : '', 'uploads' => $up, 'relay' => false, 'hasRelayKey' => false, 'publicUrl' => wb_site_url($s), 'hosted' => wb_site_hosted_here($c, $s)); });
wb_route('GET', '/sites/:id/single.html', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'publish'); $f = wb_published_html_path($c, $s); if (!is_file($f)) { throw new WbHttpError(422, '아직 게시한 적이 없습니다. 먼저 [게시하기]를 실행해 주세요.'); } wb_send_file(200, 'text/html; charset=utf-8', file_get_contents($f), 'index.html'); return null; });
wb_route('GET', '/sites/:id/bundle', function ($c, $p) { return array('__raw' => wb_bundle($c, wb_site_of($c, $p['id']))); });
wb_route('POST', '/sites/:id/preview', function ($c, $p) { $s = wb_site_of($c, $p['id']); $data = wb_bo($c, 'data'); if (!is_object($data)) { throw new WbHttpError(422, '미리보기 데이터가 없습니다.'); } $token = wb_token(24); wb_insert('preview_tokens', array('site_id' => (int)$s['id'], 'user_id' => (int)$c['user']['id'], 'token_hash' => wb_sha256($token), 'data_json' => wb_enc($data), 'expires_at' => wb_now(time() + 1800), 'created_at' => wb_now())); wb_del('preview_tokens', 'expires_at < ?', array(wb_now())); $page = wb_str(wb_b($c, 'page'), 60); $url = wb_site_url($s) . '/index.html?cms_preview=' . $token . ($page === '' || $page === 'main' ? '' : '#page=' . rawurlencode($page)); if (function_exists('wb_preview_url_for')) { try { $url = wb_preview_url_for($c, $s, $url, $token, $page); } catch (Throwable $e) { wb_log_error('preview url: ' . $e->getMessage()); } } return array('token' => $token, 'url' => $url, 'expires' => 30); });
wb_route('GET', '/sites/:id/preview-token', function ($c, $p) { throw new WbHttpError(422, '운영 서버에서는 관리자 화면이 미리보기 데이터를 만들어 보냅니다. (POST /sites/:id/preview)'); });
wb_route('POST', '/sites/:id/publish-result', function ($c, $p) { $s0 = wb_site_of($c, $p['id'], 'publish'); if (function_exists('wb_publish_lock_set')) { wb_publish_lock_set((int)$s0['id'], wb_str(wb_b($c, 'session'), 64), false); } return wb_publish_result($c, wb_site_of($c, $p['id'], 'publish')); });
wb_route('POST', '/sites/:id/publish', function ($c, $p) { wb_site_of($c, $p['id'], 'publish'); throw new WbHttpError(422, '운영 서버에서는 관리자 화면이 게시 파일을 만들어 저장합니다. 관리자 화면을 새로 고친 뒤 다시 [게시하기]를 눌러 주세요.'); });
wb_route('GET', '/sites/:id/publish-status', function ($c, $p) { return wb_publish_state($c, wb_site_of($c, $p['id'])); });
/* 지금 공개 중인 index.html 원문 (게시 전 점검 · 이 서버가 호스팅하는 홈페이지 파일 그대로) */
wb_route('GET', '/sites/:id/publish/live', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'publish'); $f = wb_published_html_path($c, $s); $html = is_file($f) ? (string)@file_get_contents($f) : ''; return array('html' => $html, 'hosted' => wb_site_hosted_here($c, $s), 'bytes' => strlen($html)); });
wb_route('GET', '/sites/:id/publish/backups', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'publish'); return array('backups' => wb_publish_backups($s), 'current' => wb_publish_current_info($c, $s)); });
wb_route('POST', '/sites/:id/publish/backups/:name/restore', function ($c, $p) {
  $s = wb_site_of($c, $p['id'], 'publish'); $name = basename((string)$p['name']); if (!preg_match('/^index-[0-9]{8}-[0-9]{6}(-v[0-9]+)?\.html$/', $name)) { throw new WbHttpError(422, '백업 파일 이름이 올바르지 않습니다.'); }
  $src = wb_publish_backup_dir($s) . '/' . $name; if (!is_file($src)) { throw new WbHttpError(404, '백업 파일을 찾을 수 없습니다.'); }
  $html = (string)@file_get_contents($src); if (strlen($html) < 200 || stripos($html, '<html') === false) { throw new WbHttpError(422, '백업 파일 내용이 올바르지 않습니다.'); }
  $dest = wb_published_html_path($c, $s); $bk = wb_publish_backup_current($c, $s, 'before-restore');
  if (!wb_write_atomic($dest, $html)) { throw new WbHttpError(500, '공개 홈페이지 파일(index.html)을 쓸 수 없습니다. 파일 권한을 확인해 주세요.'); }
  wb_log($c, (int)$s['id'], 'site.publish_restore', 'site', (int)$s['id'], '공개 홈페이지 복원 · ' . $name . ($bk ? ' (복원 직전 상태 백업 ' . $bk . ')' : ''));
  return array('ok' => true, 'restored' => $name, 'backup' => $bk, 'publicUrl' => wb_site_url($s) . '/index.html');
});
wb_route('GET', '/sites/:id/snapshots', function ($c, $p) { $s = wb_site_of($c, $p['id']); $rows = array(); foreach (wb_all('SELECT v.id, v.version_no, v.note, v.created_at, v.deployed, v.status, v.result_json, v.summary_json, u.name AS user_name, LENGTH(v.content_json) AS bytes FROM publish_snapshots v LEFT JOIN users u ON u.id = v.created_by WHERE v.site_id = ? ORDER BY v.id DESC LIMIT 100', array((int)$s['id'])) as $r) { $res = wb_json_safe($r['result_json'], null); $r = wb_ints($r, array('id', 'version_no', 'bytes')); unset($r['result_json']); $r['status'] = $r['status'] ? $r['status'] : 'published'; $r['error'] = $res ? (string)wb_prop($res, 'error', '') : ''; $r['summary'] = wb_json_safe($r['summary_json'], null); $r['current'] = (int)$r['id'] === (int)$s['published_snapshot_id']; $rows[] = $r; } return array('snapshots' => $rows, 'current' => $s['published_snapshot_id'] ? (int)$s['published_snapshot_id'] : null); });
wb_route('GET', '/sites/:id/snapshots/:sid', function ($c, $p) { $s = wb_site_of($c, $p['id']); $snap = wb_get('SELECT * FROM publish_snapshots WHERE id = ? AND site_id = ?', array((int)$p['sid'], (int)$s['id'])); if (!$snap) { throw new WbHttpError(404, '없음'); } return array('snapshot' => array('id' => (int)$snap['id'], 'version_no' => (int)$snap['version_no'], 'note' => $snap['note'], 'created_at' => $snap['created_at'], 'content' => wb_json_safe($snap['content_json'], new stdClass()))); });
wb_route('POST', '/sites/:id/snapshots/:sid/restore', function ($c, $p) { wb_site_of($c, $p['id'], 'publish'); throw new WbHttpError(422, '운영 서버에서는 관리자 화면이 복원 게시를 처리합니다. 화면을 새로 고친 뒤 다시 시도해 주세요.'); });
wb_route('GET', '/sites/compiled', function ($c) { throw new WbHttpError(422, '운영 서버에서는 관리자 화면이 컴파일합니다.'); });
wb_route('GET', '/sites/:id/compiled', function ($c, $p) { throw new WbHttpError(422, '운영 서버에서는 관리자 화면이 컴파일합니다.'); });

/* ================= 설정 · 메뉴 ================= */
function wb_validate_settings($group, $data) {
  $bad = function ($label, $why) { throw new WbHttpError(422, $label . ' : ' . $why, array('field' => $label)); };
  $tel = function ($v, $l) use ($bad) { if ($v === null || $v === '') { return; } $v = trim((string)$v); if (!preg_match('/^[0-9+\-() .]{4,24}$/', $v) || strlen(preg_replace('/[^0-9]/', '', $v)) < 7) { $bad($l, '전화번호 형식이 올바르지 않습니다. (예 1600-0000 · 02-123-4567)'); } };
  $mail = function ($v, $l) use ($bad) { if ($v === null || $v === '') { return; } if (!preg_match('/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/', trim((string)$v))) { $bad($l, '이메일 형식이 올바르지 않습니다.'); } };
  $url = function ($v, $l) use ($bad) { if ($v === null || $v === '') { return; } if (!preg_match('/^https?:\/\/[^\s]+$/i', trim((string)$v))) { $bad($l, '주소는 http:// 또는 https:// 로 시작해야 합니다.'); } };
  $color = function ($v, $l) use ($bad) { if ($v === null || $v === '') { return; } if (!preg_match('/^(#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})|rgba?\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*(,\s*(0|1|0?\.\d+)\s*)?\))$/i', trim((string)$v))) { $bad($l, '색상은 #002F47 · rgb(0,47,71) · rgba(0,47,71,.5) 형식으로 입력해 주세요.'); } };
  if ($group === 'site' && is_array(wb_prop($data, 'site'))) { $s = $data['site']; $tel(isset($s['tel']) ? $s['tel'] : null, '대표번호'); $tel(isset($s['smsTel']) ? $s['smsTel'] : null, '문자 문의 번호'); $tel(isset($s['mobile']) ? $s['mobile'] : null, '휴대전화번호'); $mail(isset($s['email']) ? $s['email'] : null, '대표 이메일'); $mail(isset($s['reserveEmail']) ? $s['reserveEmail'] : null, '방문예약 담당자 이메일'); $url(isset($s['kakaoUrl']) ? $s['kakaoUrl'] : null, '카카오톡 상담 링크'); $url(isset($s['naverMap']) ? $s['naverMap'] : null, '네이버지도 링크'); $url(isset($s['kakaoMap']) ? $s['kakaoMap'] : null, '카카오지도 링크'); }
  if ($group === 'footer' && is_array(wb_prop($data, 'footer'))) { $tel(isset($data['footer']['phoneDisplay']) ? $data['footer']['phoneDisplay'] : null, '푸터 대표번호'); $mail(isset($data['footer']['email']) ? $data['footer']['email'] : null, '푸터 이메일'); }
  if ($group === 'design' && is_array($data)) { foreach (array('brandColor' => '메인 브랜드 컬러', 'secondaryColor' => '보조 컬러', 'accentColor' => '강조 컬러', 'textColor' => '기본 진한 글자색', 'textLightColor' => '기본 밝은 글자색', 'backgroundColor' => '기본 배경색', 'buttonColor' => '버튼 기본 컬러', 'buttonHoverColor' => '버튼 호버 컬러', 'buttonTextColor' => '버튼 글자색', 'linkColor' => '링크 · 활성 메뉴 컬러', 'overlayColor' => '오버레이 컬러') as $k => $l) { $color(isset($data[$k]) ? $data[$k] : null, $l); } if (isset($data['overlayOpacity']) && $data['overlayOpacity'] !== '' && !(is_numeric($data['overlayOpacity']) && (float)$data['overlayOpacity'] >= 0 && (float)$data['overlayOpacity'] <= 1)) { $bad('오버레이 농도', '0 ~ 1 사이의 숫자로 입력해 주세요.'); } }
}
function wb_put_settings_route($c, $s, $group) { if (in_array($group, array('gsheets', 'notify'), true)) { throw new WbHttpError(403, '이 설정은 사이트 설정 › 외부 연동 화면에서 바꿀 수 있습니다.'); } $dataObj = wb_bo($c, 'data'); if (!is_object($dataObj)) { throw new WbHttpError(422, '설정 형식이 올바르지 않습니다.'); } wb_validate_settings($group, wb_arr($dataObj)); $before = wb_get_setting((int)$s['id'], $group); wb_put_setting((int)$s['id'], $group, $dataObj, (int)$c['user']['id']); if ($group === 'site' && isset($dataObj->site) && is_object($dataObj->site)) { $d = array(); $ss = $dataObj->site; if (isset($ss->tel)) { $d['tel'] = wb_str($ss->tel, 30); } if (!empty($ss->name)) { $d['name'] = wb_str($ss->name, 80); } if (isset($ss->fieldName)) { $d['field_name'] = wb_str($ss->fieldName, 80); } if (!empty($ss->url) && preg_match('#^https?://[^\s/]+#i', (string)$ss->url)) { $d['public_url'] = preg_replace('#/(index\.html)?$#', '', wb_str($ss->url, 200)); } if (count($d)) { $d['updated_at'] = wb_now(); wb_update('sites', $d, 'id = ?', array((int)$s['id'])); } } wb_log($c, (int)$s['id'], 'settings.update', 'settings', null, $group . ' 설정 변경', $before, $dataObj); return array('group' => $group); }
wb_route('GET', '/sites/:id/settings/:group', function ($c, $p) { $s = wb_site_of($c, $p['id']); return array('group' => $p['group'], 'data' => wb_get_setting((int)$s['id'], $p['group'])); });
wb_route('PUT', '/sites/:id/settings/:group', function ($c, $p) { return wb_put_settings_route($c, wb_site_of($c, $p['id'], 'manage'), $p['group']); });
wb_route('GET', '/settings/:group', function ($c, $p) { $s = wb_current_site($c); return array('group' => $p['group'], 'data' => wb_get_setting((int)$s['id'], $p['group'])); });
wb_route('PUT', '/settings/:group', function ($c, $p) { return wb_put_settings_route($c, wb_current_site($c, 'manage'), $p['group']); });
function wb_compile_menu($siteId) { $menu = wb_get("SELECT id FROM menus WHERE site_id = ? AND `key` = 'main'", array((int)$siteId)); if (!$menu) { return array(); } $items = wb_all('SELECT * FROM menu_items WHERE menu_id = ? ORDER BY sort, id', array((int)$menu['id'])); $out = array(); foreach ($items as $g) { if (!empty($g['parent_id'])) { continue; } $children = array(); foreach ($items as $ch) { if ((int)$ch['parent_id'] !== (int)$g['id']) { continue; } $it = array('enabled' => (int)$ch['enabled'] === 1, 'page' => (string)$ch['page_key'], 'label' => $ch['label']); if ($ch['link_type'] === 'url' && !empty($ch['url'])) { $it['url'] = $ch['url']; $it['target'] = $ch['target'] ? $ch['target'] : '_self'; } $children[] = $it; } $out[] = array('enabled' => (int)$g['enabled'] === 1, 'id' => $g['page_key'] ? $g['page_key'] : $g['label'], 'label' => $g['label'], 'latin' => (string)$g['latin'], 'items' => $children); } return $out; }
wb_route('GET', '/sites/:id/menus/main', function ($c, $p) { $s = wb_site_of($c, $p['id']); return array('menu' => wb_compile_menu((int)$s['id']), 'pages' => array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all('SELECT id, `key`, title, status FROM pages WHERE site_id = ? AND deleted_at IS NULL ORDER BY sort', array((int)$s['id'])))); });
wb_route('PUT', '/sites/:id/menus/main', function ($c, $p) { $s = wb_site_of($c, $p['id'], 'manage'); $menu = wb_b($c, 'menu'); if (!is_array($menu)) { throw new WbHttpError(422, '메뉴 형식이 올바르지 않습니다.'); } wb_tx(function () use ($s, $menu) { $m = wb_get("SELECT id FROM menus WHERE site_id = ? AND `key` = 'main'", array((int)$s['id'])); $mid = $m ? (int)$m['id'] : wb_insert('menus', array('site_id' => (int)$s['id'], 'key' => 'main', 'name' => '메인 메뉴', 'updated_at' => wb_now())); wb_del('menu_items', 'menu_id = ?', array($mid)); $sort = 0; foreach ($menu as $g) { $g = wb_arr($g); $pid = wb_insert('menu_items', array('menu_id' => $mid, 'parent_id' => null, 'label' => wb_str(isset($g['label']) ? $g['label'] : '', 60), 'latin' => wb_str(isset($g['latin']) ? $g['latin'] : '', 60), 'link_type' => 'group', 'page_key' => wb_str(isset($g['id']) ? $g['id'] : '', 60), 'url' => '', 'target' => '_self', 'sort' => $sort++, 'enabled' => (isset($g['enabled']) && $g['enabled'] === false) ? 0 : 1)); $cs = 0; foreach ((array)(isset($g['items']) ? $g['items'] : array()) as $it) { $it = wb_arr($it); wb_insert('menu_items', array('menu_id' => $mid, 'parent_id' => $pid, 'label' => wb_str(isset($it['label']) ? $it['label'] : '', 60), 'latin' => '', 'link_type' => !empty($it['url']) ? 'url' : 'page', 'page_key' => wb_str(isset($it['page']) ? $it['page'] : '', 60), 'url' => wb_str(isset($it['url']) ? $it['url'] : '', 500), 'target' => wb_str(!empty($it['target']) ? $it['target'] : '_self', 20), 'sort' => $cs++, 'enabled' => (isset($it['enabled']) && $it['enabled'] === false) ? 0 : 1)); } } wb_update('menus', array('updated_at' => wb_now()), 'id = ?', array($mid)); }); wb_log($c, (int)$s['id'], 'menu.update', 'menu', null, '메뉴 수정'); return array(); });

/* ================= 페이지 · 에디터 ================= */
/* 내용이 비어 있는 페이지 수 (메인이 비면 홈 화면 · 공통 내용이 비어 게시가 위험) */
/* 게시본 버전의 구성 개수 (게시 파일은 이 값으로 만들어집니다 — 여기가 0 이면 공개 홈페이지가 빈 화면이 됩니다) */
function wb_published_sections_count($row) {
  if (!$row || empty($row['published_version_id'])) { return -1; }
  $v = wb_get('SELECT content_json FROM page_versions WHERE id = ?', array((int)$row['published_version_id']));
  if (!$v) { return -1; }
  $j = wb_json_safe($v['content_json'], null);
  if (!is_object($j)) { return -1; }
  return isset($j->sections) && is_array($j->sections) ? count($j->sections) : 0;
}
function wb_pages_empty_info($siteId) {
  $empty = array(); $mainEmpty = false; $mainPubEmpty = false;
  foreach (wb_all('SELECT * FROM pages WHERE site_id = ? AND deleted_at IS NULL', array((int)$siteId)) as $r) {
    if (function_exists('wb_import_page_empty') && wb_import_page_empty($r)) { $empty[] = (string)$r['key']; if ((string)$r['type'] === 'main') { $mainEmpty = true; } }
    if ((string)$r['type'] === 'main' && (string)$r['status'] === 'published' && wb_published_sections_count($r) === 0) { $mainPubEmpty = true; }   /* 초안은 멀쩡한데 게시본만 비어 있는 경우 */
  }
  return array('emptyPages' => $empty, 'mainEmpty' => $mainEmpty, 'mainPublishedEmpty' => $mainPubEmpty, 'needsRepairMain' => ($mainEmpty || $mainPubEmpty));
}
wb_route('GET', '/sites/:id/pages', function ($c, $p) { $s = wb_site_of($c, $p['id']); $types = array(); foreach (wb_section_names() as $k => $n) { $types[] = array('key' => $k, 'name' => $n, 'scope' => 'main', 'fields' => array()); } $emptyInfo = wb_pages_empty_info((int)$s['id']); return array_merge($emptyInfo, array('needsImport' => $emptyInfo['mainEmpty'] || count($emptyInfo['emptyPages']) > 0), array('pages' => array_map('wb_page_row', wb_all('SELECT * FROM pages WHERE site_id = ? AND deleted_at IS NULL ORDER BY sort, id', array((int)$s['id']))), 'statuses' => wb_page_status_names(), 'layouts' => wb_layouts(), 'forms' => array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all('SELECT id, `key`, name FROM forms WHERE site_id = ?', array((int)$s['id']))), 'popups' => array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all("SELECT id, name FROM popups WHERE site_id = ? AND status <> 'deleted'", array((int)$s['id']))), 'types' => $types));});
wb_route('POST', '/sites/:id/pages/main', function ($c, $p) {
  $s = wb_site_of($c, $p['id'], 'edit'); $old = wb_get("SELECT id FROM pages WHERE site_id = ? AND deleted_at IS NULL AND (type = 'main' OR `key` = 'main') ORDER BY id LIMIT 1", array((int)$s['id']));
  if ($old) { return array('id' => (int)$old['id'], 'created' => false); }
  foreach (wb_all("SELECT id FROM pages WHERE site_id = ? AND `key` = 'main' AND deleted_at IS NOT NULL", array((int)$s['id'])) as $dr) { wb_run('UPDATE pages SET `key` = ? WHERE id = ?', array('main-deleted-' . (int)$dr['id'], (int)$dr['id'])); }
  $id = wb_create_page((int)$s['id'], 'main', '메인', 'main', array('sections' => array(), 'styles' => new stdClass()), (int)$c['user']['id'], 0, false);
  wb_log($c, (int)$s['id'], 'page.create', 'page', (int)$id, '메인 페이지 생성 (빈 페이지)'); return array('id' => (int)$id, 'created' => true);
});
wb_route('POST', '/pages', function ($c) { $s = wb_current_site($c, 'edit'); $key = wb_keyify(wb_b($c, 'key')); if ($key === '') { throw new WbHttpError(422, '페이지 키(영문 · 숫자)를 입력해 주세요.'); } if (wb_get('SELECT id FROM pages WHERE site_id = ? AND `key` = ?', array((int)$s['id'], $key))) { throw new WbHttpError(422, '이미 있는 페이지 키입니다.'); } $sort = wb_int(wb_val('SELECT COALESCE(MAX(sort), 0) + 1 FROM pages WHERE site_id = ?', array((int)$s['id'])), 1); $title = wb_str(wb_b($c, 'title'), 150) ?: $key; $layout = wb_str(wb_b($c, 'layout_type', 'text'), 40) ?: 'text'; $id = wb_create_page((int)$s['id'], $key, $title, 'sub', array('page' => array('enabled' => true, 'title' => $title, 'category' => wb_str(wb_b($c, 'category'), 60), 'layoutType' => $layout, 'description' => '', 'sections' => array()), 'sections' => array(), 'styles' => new stdClass(), 'hidden' => new stdClass()), (int)$c['user']['id'], $sort, false, $layout, wb_str(wb_b($c, 'category'), 60)); wb_log($c, (int)$s['id'], 'page.create', 'page', $id, '페이지 생성 ' . $key); return array('id' => $id); });
wb_route('POST', '/pages/:id/duplicate', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'edit'); if ($pg['type'] === 'main') { throw new WbHttpError(422, '메인 페이지는 복제할 수 없습니다.'); } $key = $pg['key'] . '-copy'; $i = 2; while (wb_get('SELECT id FROM pages WHERE site_id = ? AND `key` = ?', array((int)$pg['site_id'], $key))) { $key = $pg['key'] . '-copy' . ($i++); } $content = wb_page_content(wb_draft_version($pg)); if (!isset($content->page) || !is_object($content->page)) { $content->page = new stdClass(); } $content->page->title = (isset($content->page->title) && $content->page->title !== '' ? $content->page->title : $pg['title']) . ' 복사본'; $id = wb_create_page((int)$pg['site_id'], $key, $pg['title'] . ' 복사본', 'sub', $content, (int)$c['user']['id'], (int)$pg['sort'] + 1, false, $pg['layout_type'], $pg['category']); wb_log($c, (int)$pg['site_id'], 'page.duplicate', 'page', $id, '페이지 복제 ' . $pg['key']); return array('id' => $id); });
wb_route('GET', '/pages/:id/draft', function ($c, $p) { $pg = wb_page_of($c, $p['id']); $v = wb_draft_version($pg, false);   /* 열기만 할 때는 초안을 분리하지 않음 (상태가 '게시 대기' 로 바뀌지 않게) */ return array('page' => wb_page_row($pg), 'content' => wb_page_content($v), 'version' => array('id' => (int)$v['id'], 'no' => (int)$v['version_no']), 'compiled' => null); });
wb_route('PUT', '/pages/:id/draft', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'edit'); $content = wb_bo($c, 'content'); if (!is_object($content)) { throw new WbHttpError(422, '내용 형식이 올바르지 않습니다.'); } $snap = wb_bool(wb_b($c, 'snapshot')); $baseRev = wb_str(wb_b($c, 'base_rev'), 30); if ($baseRev !== '' && !wb_bool(wb_b($c, 'overwrite'))) {   $curRev = (string)$pg['updated_at'];   if ($curRev !== '' && strcmp($curRev, $baseRev) > 0) {     $lastBy = wb_val('SELECT u.name FROM page_versions v LEFT JOIN users u ON u.id = v.created_by WHERE v.id = ?', array((int)$pg['draft_version_id']));     if ($lastBy !== null && (int)wb_val('SELECT created_by FROM page_versions WHERE id = ?', array((int)$pg['draft_version_id'])) !== (int)$c['user']['id']) {       throw new WbHttpError(409, '다른 사용자(' . (string)$lastBy . ')가 이 페이지를 먼저 수정했습니다.', array('code' => 'REVISION', 'by' => (string)$lastBy, 'rev' => $curRev));     }   } } $r = wb_save_draft($pg, $content, $snap, wb_str(wb_b($c, 'note'), 250), (int)$c['user']['id']); if ($snap) { wb_log($c, (int)$pg['site_id'], 'page.save', 'page', (int)$pg['id'], '임시저장 ' . $pg['title'] . (wb_b($c, 'note') ? ' · ' . wb_b($c, 'note') : '')); } $r['saved_at'] = wb_now(); return $r; });
wb_route('POST', '/pages/:id/publish-check', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'edit'); $content = wb_bo($c, 'content'); if (is_object($content)) { wb_save_draft($pg, $content, false, '', (int)$c['user']['id']); } return wb_publish_check(wb_get('SELECT * FROM sites WHERE id = ?', array((int)$pg['site_id'])), (int)$pg['id']); });
wb_route('POST', '/pages/:id/publish', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'publish'); $sess = wb_str(wb_b($c, 'session'), 64); if (function_exists('wb_publish_locked_by')) { $by = wb_publish_locked_by((int)$pg['site_id'], $sess); if ($by !== '') { throw new WbHttpError(409, '지금 ' . $by . ' 님이 게시 중입니다. 끝난 뒤 다시 시도해 주세요.', array('code' => 'PUBLISH_LOCK')); } wb_publish_lock_set((int)$pg['site_id'], $sess, true); } $site = wb_get('SELECT * FROM sites WHERE id = ?', array((int)$pg['site_id'])); $content = wb_bo($c, 'content'); if (is_object($content)) { wb_save_draft($pg, $content, false, '', (int)$c['user']['id']); } $check = wb_publish_check($site, (int)$pg['id']); if ($check['hasErrors'] && !wb_bool(wb_b($c, 'force'))) { $errs = array(); foreach ($check['issues'] as $i) { if ($i['level'] === 'error') { $errs[] = $i['text']; } } throw new WbHttpError(422, '게시 전 점검에서 오류가 있습니다: ' . implode(' / ', $errs)); } wb_publish_page($pg, wb_str(wb_b($c, 'note')) ?: '게시', (int)$c['user']['id']); wb_log($c, (int)$pg['site_id'], 'page.publish', 'page', (int)$pg['id'], '페이지 게시본 확정 ' . $pg['title']); return array('ok' => true, 'pageOnly' => true, 'needsSitePublish' => true, 'summary' => $check['summary']); });
wb_route('POST', '/pages/:id/review', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'edit'); wb_update('pages', array('status' => 'review', 'updated_at' => wb_now()), 'id = ?', array((int)$pg['id'])); wb_log($c, (int)$pg['site_id'], 'page.review', 'page', (int)$pg['id'], '검토 요청 ' . $pg['title']); return array(); });
wb_route('POST', '/pages/:id/schedule', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'publish'); $content = wb_bo($c, 'content'); if (is_object($content)) { wb_save_draft($pg, $content, true, '예약 게시 등록', (int)$c['user']['id']); } $at = substr(str_replace('T', ' ', wb_str(wb_b($c, 'publish_at'))), 0, 16) . ':00'; if (!preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/', $at)) { throw new WbHttpError(422, '게시 일시 형식이 올바르지 않습니다.'); } wb_update('pages', array('status' => 'scheduled', 'publish_at' => $at, 'updated_at' => wb_now()), 'id = ?', array((int)$pg['id'])); wb_log($c, (int)$pg['site_id'], 'page.schedule', 'page', (int)$pg['id'], '예약 게시 ' . $at); return array('publish_at' => $at); });
wb_route('POST', '/pages/:id/unpublish', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'publish'); if ($pg['type'] === 'main') { throw new WbHttpError(422, '메인 페이지는 게시 중지할 수 없습니다.'); } wb_update('pages', array('status' => 'stopped', 'publish_at' => null, 'updated_at' => wb_now()), 'id = ?', array((int)$pg['id'])); wb_log($c, (int)$pg['site_id'], 'page.unpublish', 'page', (int)$pg['id'], '게시 중지 ' . $pg['title']); return array('needsSitePublish' => true); });
wb_route('GET', '/pages/:id/versions', function ($c, $p) { return array('versions' => wb_versions((int)wb_page_of($c, $p['id'])['id'])); });
wb_route('GET', '/pages/:id/versions/:vid', function ($c, $p) { $pg = wb_page_of($c, $p['id']); $v = wb_get('SELECT * FROM page_versions WHERE id = ? AND page_id = ?', array((int)$p['vid'], (int)$pg['id'])); if (!$v) { throw new WbHttpError(404, '버전을 찾을 수 없습니다.'); } return array('content' => wb_page_content($v), 'version' => array('id' => (int)$v['id'], 'no' => (int)$v['version_no'], 'status' => $v['status'], 'created_at' => $v['created_at'])); });
wb_route('POST', '/pages/:id/versions/:vid/restore', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'edit'); $v = wb_get('SELECT * FROM page_versions WHERE id = ? AND page_id = ?', array((int)$p['vid'], (int)$pg['id'])); if (!$v) { throw new WbHttpError(404, '버전을 찾을 수 없습니다.'); } wb_save_draft($pg, wb_page_content($v), true, 'v' . $v['version_no'] . ' 복원', (int)$c['user']['id']); wb_log($c, (int)$pg['site_id'], 'page.restore', 'page', (int)$pg['id'], '버전 복원 ' . $pg['title']); return array(); });
wb_route('GET', '/pages/trash', function ($c) { $s = wb_current_site($c); return array('pages' => array_map(function ($r) { return wb_ints($r, array('id')); }, wb_all('SELECT id, `key`, title, deleted_at FROM pages WHERE site_id = ? AND deleted_at IS NOT NULL ORDER BY deleted_at DESC LIMIT 50', array((int)$s['id'])))); });
wb_route('POST', '/pages/reorder', function ($c) { $s = wb_current_site($c, 'edit'); $i = 0; foreach ((array)wb_b($c, 'ids', array()) as $id) { wb_update('pages', array('sort' => $i++), 'id = ? AND site_id = ?', array(wb_int($id), (int)$s['id'])); } return array(); });
wb_route('PATCH', '/pages/:id/meta', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'edit'); $b = $c['body']; $d = array(); if (wb_has($b, 'title')) { $d['title'] = wb_str($b['title'], 150); } if (wb_has($b, 'category')) { $d['category'] = wb_str($b['category'], 60); } if (wb_has($b, 'layout_type')) { $d['layout_type'] = wb_str($b['layout_type'], 40); } if (wb_has($b, 'visible')) { if ($pg['type'] === 'main') { throw new WbHttpError(422, '메인 페이지는 항상 공개됩니다.'); } $vis = wb_bool($b['visible']); $d['status'] = $vis ? ($pg['published_version_id'] ? 'published' : 'draft') : 'stopped'; if (!$vis) { $d['publish_at'] = null; } } $d['updated_at'] = wb_now(); wb_update('pages', $d, 'id = ?', array((int)$pg['id'])); if (isset($d['status'])) { wb_log($c, (int)$pg['site_id'], $d['status'] === 'stopped' ? 'page.hide' : 'page.show', 'page', (int)$pg['id'], ($d['status'] === 'stopped' ? '페이지 숨김 ' : '페이지 공개 ') . $pg['title']); } if (isset($d['title']) && $d['title'] !== $pg['title']) { wb_log($c, (int)$pg['site_id'], 'page.rename', 'page', (int)$pg['id'], '페이지 이름 변경 ' . $pg['title'] . ' → ' . $d['title']); } return array('status' => isset($d['status']) ? $d['status'] : $pg['status']); });
wb_route('DELETE', '/pages/:id', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'edit'); if ($pg['type'] === 'main') { throw new WbHttpError(422, '메인 페이지는 삭제할 수 없습니다.'); } wb_update('pages', array('deleted_at' => wb_now(), 'updated_at' => wb_now()), 'id = ?', array((int)$pg['id'])); wb_log($c, (int)$pg['site_id'], 'page.delete', 'page', (int)$pg['id'], '페이지 휴지통 ' . $pg['title']); return array(); });
wb_route('POST', '/pages/:id/restore', function ($c, $p) { $pg = wb_page_of($c, $p['id'], 'edit', true); wb_update('pages', array('deleted_at' => null, 'updated_at' => wb_now()), 'id = ?', array((int)$pg['id'])); wb_log($c, (int)$pg['site_id'], 'page.restore_trash', 'page', (int)$pg['id'], '휴지통 복구 ' . $pg['title']); return array(); });
wb_route('GET', '/blocks', function ($c) { $s = wb_current_site($c); return array('blocks' => array_map(function ($b) { return array('id' => (int)$b['id'], 'key' => $b['key'], 'name' => $b['name'], 'section' => wb_json_safe($b['fields_json'], new stdClass())); }, wb_all("SELECT id, `key`, name, fields_json FROM section_types WHERE site_id = ? AND scope = 'saved' ORDER BY sort, id", array((int)$s['id'])))); });
wb_route('POST', '/blocks', function ($c) { $s = wb_current_site($c, 'edit'); $sec = wb_bo($c, 'section'); if (!is_object($sec) || empty($sec->type)) { throw new WbHttpError(422, '저장할 섹션 정보가 없습니다.'); } $id = wb_insert('section_types', array('site_id' => (int)$s['id'], 'key' => 'saved-' . substr(wb_hex(4), 0, 6), 'name' => wb_str(wb_b($c, 'name'), 120) ?: '저장한 블록', 'scope' => 'saved', 'fields_json' => wb_enc($sec), 'sort' => wb_int(wb_val('SELECT COUNT(*) FROM section_types WHERE site_id = ?', array((int)$s['id']))))); return array('id' => $id); });
wb_route('DELETE', '/blocks/:id', function ($c, $p) { $s = wb_current_site($c, 'edit'); wb_del('section_types', "id = ? AND site_id = ? AND scope = 'saved'", array((int)$p['id'], (int)$s['id'])); return array(); });

/* ================= 폼 ================= */
function wb_form_of($c, $id, $ability = 'view') { $f = wb_get('SELECT * FROM forms WHERE id = ?', array((int)$id)); if (!$f) { throw new WbHttpError(404, '폼을 찾을 수 없습니다.'); } wb_site_of($c, (int)$f['site_id'], $ability); return $f; }
wb_route('GET', '/sites/:id/forms', function ($c, $p) { $s = wb_site_of($c, $p['id']); return array('forms' => array_map(function ($f) { return array('id' => (int)$f['id'], 'key' => $f['key'], 'name' => $f['name'], 'version' => (int)$f['version'], 'status' => $f['status'], 'updated_at' => $f['updated_at'], 'has_draft' => !empty($f['draft_json'])); }, wb_all('SELECT id, `key`, name, version, status, updated_at, draft_json FROM forms WHERE site_id = ?', array((int)$s['id'])))); });
wb_route('GET', '/forms/:id', function ($c, $p) { $f = wb_form_of($c, $p['id']); $draft = wb_form_draft((int)$f['id']); return array('schema' => $draft ? $draft : wb_form_schema((int)$f['id']), 'published' => wb_form_schema((int)$f['id']), 'hasDraft' => (bool)$draft); });
wb_route('PUT', '/forms/:id', function ($c, $p) { $f = wb_form_of($c, $p['id'], 'edit'); $base = wb_form_draft((int)$f['id']); if (!$base) { $base = wb_form_schema((int)$f['id']); } $settingsObj = wb_bo($c, 'settings'); $settings = is_object($settingsObj) ? $settingsObj : $base['settings']; if (is_array($settings)) { $settings = (object)$settings; } if (!isset($settings->visitTimes) || !is_array($settings->visitTimes) || !count($settings->visitTimes)) { $settings->visitTimes = wb_visit_times(); } $fields = is_array(wb_b($c, 'fields')) ? wb_b($c, 'fields') : $base['fields']; $seen = array(); foreach ($fields as $x) { $x = wb_arr($x); $k = preg_replace('/[^a-zA-Z0-9_]/', '', wb_str(isset($x['name']) ? $x['name'] : '')); if ($k === '') { throw new WbHttpError(422, '필드 이름(영문)이 비어 있는 항목이 있습니다 : ' . wb_str(isset($x['label']) ? $x['label'] : '')); } if (isset($seen[$k])) { throw new WbHttpError(422, '필드 이름(영문)이 겹칩니다 : ' . $k); } $seen[$k] = true; } $pub = wb_form_schema((int)$f['id']); $same = wb_enc(array('s' => wb_arr($settings), 'f' => wb_normalize_fields($fields))) === wb_enc(array('s' => wb_arr($pub['settings']), 'f' => wb_normalize_fields($pub['fields']))); if ($same) { wb_discard_form_draft((int)$f['id']); } else { wb_save_form_draft((int)$f['id'], $settings, $fields, (int)$c['user']['id']); } if (wb_b($c, 'name')) { wb_update('forms', array('name' => wb_str(wb_b($c, 'name'), 120)), 'id = ?', array((int)$f['id'])); } if (!wb_bool(wb_b($c, 'quiet'))) { wb_log($c, (int)$f['site_id'], 'form.update', 'form', (int)$f['id'], '폼 초안 저장 ' . $f['name']); } $draft = wb_form_draft((int)$f['id']); return array('schema' => $draft ? $draft : wb_form_schema((int)$f['id']), 'hasDraft' => (bool)$draft); });
wb_route('DELETE', '/forms/:id/draft', function ($c, $p) { $f = wb_form_of($c, $p['id'], 'edit'); wb_discard_form_draft((int)$f['id']); wb_log($c, (int)$f['site_id'], 'form.discard', 'form', (int)$f['id'], '폼 초안 버림 ' . $f['name']); return array('schema' => wb_form_schema((int)$f['id']), 'hasDraft' => false); });
